# -*- coding: utf-8 -*-
"""Seaborn_new_assignment_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12W667XZKAguRqQAemwz3H2YNDhb9ojtj
"""

#Seaborn Assignment
#Question.1 Name any five plots that we can plot using the Seaborn library. Also, state the uses of each plot.
#Answer.1 Seaborn is a powerful Python data visualization library built on top of Matplotlib. It provides a high-level interface
#for creating informative and attractive statistical graphics. Here are five types of plots that you can create using Seaborn, along
#with their typical uses:

#1.Histograms (sns.histplot):

#Use: Histograms are used to visualize the distribution of a single variable.
#Use Cases: Explore data distribution, identify modes, skewness, and outliers.

#2.Scatter Plots (sns.scatterplot):

#Use: Scatter plots show the relationship between two variables by placing data points on a two-dimensional grid.
#Use Cases: Investigate correlation between variables, identify clusters, patterns, or trends.

#3.Box Plots (sns.boxplot):

#Use: Box plots display the summary statistics (median, quartiles, potential outliers) of a dataset.
#Use Cases: Visualize the spread and skewness of data, identify outliers, compare distributions.

#4.Bar Plots (sns.barplot):
#Use: Bar plots are used to represent categorical data by showing the mean (or other summary statistic) of
#a numeric variable for different categories.
#Use Cases: Compare data across categories, display aggregated information, show differences between groups.

#5.Heatmaps (sns.heatmap):

#Use: Heatmaps display a 2D dataset using color variations to represent values.
#Use Cases: Visualize correlations, show relationships between two categorical variables, display matrices.

#Question.2 Load the "fmri" dataset using the load_dataset function of seaborn. Plot a line plot using x =
#"timepoint" and y = "signal" for different events and regions.
#Answer.2 :
import seaborn as sns
import matplotlib.pyplot as plt

# Load the "fmri" dataset
fmri_data = sns.load_dataset("fmri")

# Create a line plot using Seaborn
plt.figure(figsize=(10, 6))
sns.lineplot(data=fmri_data, x="timepoint", y="signal", hue="event", style="region", markers=True)

# Add title and labels
plt.title("Line Plot of Signal Over Time by Event and Region")
plt.xlabel("Timepoint")
plt.ylabel("Signal")

# Show legend
plt.legend(title="Event")

# Display the plot
plt.show()

#Question.3 Load the "titanic" dataset using the load_dataset function of seaborn. Plot two box plots using x =
#'pclass', y = 'age' and y = 'fare'.
#Note: pclass, age, and fare are columns in the titanic dataset.
#Answer.3 :
import seaborn as sns
import matplotlib.pyplot as plt

# Load the "titanic" dataset
titanic_data = sns.load_dataset("titanic")

# Create two box plots using Seaborn
plt.figure(figsize=(12, 6))

# Box plot for 'age' by 'pclass'
plt.subplot(1, 2, 1)
sns.boxplot(data=titanic_data, x='pclass', y='age')
plt.title("Box Plot of Age by Pclass")
plt.xlabel("Pclass")
plt.ylabel("Age")

# Box plot for 'fare' by 'pclass'
plt.subplot(1, 2, 2)
sns.boxplot(data=titanic_data, x='pclass', y='fare')
plt.title("Box Plot of Fare by Pclass")
plt.xlabel("Pclass")
plt.ylabel("Fare")

# Adjust layout and display the plots
plt.tight_layout()
plt.show()

#Question.4 Use the "diamonds" dataset from seaborn to plot a histogram for the 'price' column. Use the hue
#parameter for the 'cut' column of the diamonds dataset.
#Answer.4 :
import seaborn as sns
import matplotlib.pyplot as plt

# Load the "diamonds" dataset
diamonds_data = sns.load_dataset("diamonds")

# Create a histogram with hue using Seaborn
plt.figure(figsize=(10, 6))
sns.histplot(data=diamonds_data, x='price', hue='cut', multiple='stack', bins=30)

# Add title and labels
plt.title("Histogram of Diamond Prices by Cut")
plt.xlabel("Price")
plt.ylabel("Frequency")

# Show legend
plt.legend(title="Cut")

# Display the plot
plt.show()

#Question.5 Use the "iris" dataset from seaborn to plot a pair plot. Use the hue parameter for the "species" column
#of the iris dataset.
#Answer.5 :
import seaborn as sns
import matplotlib.pyplot as plt

# Load the "iris" dataset
iris_data = sns.load_dataset("iris")

# Create a pair plot with hue using Seaborn
sns.set(style="ticks")
sns.pairplot(iris_data, hue="species")

# Display the plot
plt.show()

#Question.6 Use the "flights" dataset from seaborn to plot a heatmap.
#Answer.6 :
import seaborn as sns
import matplotlib.pyplot as plt

# Load the "flights" dataset
flights_data = sns.load_dataset("flights")

# Pivot the data to create a matrix suitable for a heatmap
flights_pivot = flights_data.pivot_table(index='month', columns='year', values='passengers')

# Create a heatmap using Seaborn
plt.figure(figsize=(10, 6))
sns.heatmap(data=flights_pivot, cmap='YlGnBu', annot=True, fmt="d", linewidths=.5)

# Add title and labels
plt.title("Flights Heatmap")
plt.xlabel("Year")
plt.ylabel("Month")

# Display the plot
plt.show()