{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ad07b50f-03cb-4265-b7f5-bc8cf97b3511",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Statistics Assignment.2 \n",
    "#Question.1 What are the three measures of central tendency?\n",
    "#Answer.1 In statistics, the three measures of central tendency are:\n",
    "\n",
    "#Mean: The mean, often referred to as the average, is calculated by summing up\n",
    "#all the values in a dataset and then dividing by the number of values. It represents\n",
    "#the \"center\" of the data distribution and is sensitive to extreme values (outliers).\n",
    "\n",
    "#Median: The median is the middle value in a dataset when the values are arranged in ascending \n",
    "#or descending order. If there's an odd number of values, the median is the middle value. If\n",
    "#there's an even number of values, the median is the average of the two middle values. The\n",
    "#median is less affected by outliers compared to the mean.\n",
    "\n",
    "#Mode: The mode is the value that appears most frequently in a dataset. There can be one\n",
    "#mode (unimodal), more than one mode (bimodal, trimodal, etc.), or no mode (no value appears \n",
    "#more than once). The mode is particularly useful for categorical or discrete data.\n",
    "\n",
    "#These measures provide different ways of summarizing the central tendency of a dataset,\n",
    "#and they can help you understand the typical or representative value within your data."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "afbbbcc8-0e3b-4af4-903a-a00a1343a058",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.2 What is the difference between the mean, median, and mode? How are they used to measure the\n",
    "#central tendency of a dataset?\n",
    "#Answer.2 The mean, median, and mode are three different measures of central tendency used to \n",
    "#describe the center or typical value of a dataset. Each measure has its own characteristics and \n",
    "#is useful in different situations:\n",
    "\n",
    "#Mean:\n",
    "\n",
    "#The mean is the average of all the values in a dataset.\n",
    "#It is calculated by summing up all the values and then dividing by the total number of values.\n",
    "#The mean is sensitive to extreme values (outliers), as it takes into account every data point.\n",
    "#It provides a balanced representation of the dataset's center.\n",
    "#The mean is commonly used in situations where the data is approximately normally distributed\n",
    "#and there are no significant outliers.\n",
    "\n",
    "#Median:\n",
    "\n",
    "#The median is the middle value of a dataset when values are arranged in ascending or descending order.\n",
    "#If there's an odd number of values, the median is the middle value itself. If there's an even number\n",
    "#of values, the median is the average of the two middle values.\n",
    "#The median is less affected by extreme values or outliers compared to the mean, making it a robust\n",
    "#measure of central tendency.\n",
    "#It is particularly useful when the data has a skewed distribution or when there are outliers that \n",
    "#might heavily influence the mean.\n",
    "\n",
    "#Mode:\n",
    "\n",
    "#The mode is the value that appears most frequently in a dataset.\n",
    "#It is used primarily for categorical or discrete data, where you're interested in identifying the\n",
    "#most common category or value.\n",
    "#A dataset can have one mode (unimodal), multiple modes (bimodal, trimodal, etc.), or no mode at all.\n",
    "#The mode is especially helpful when dealing with nominal or categorical data, such as colors, categories,\n",
    "#or labels.\n",
    "#In summary, the mean, median, and mode are all measures of central tendency that provide different\n",
    "#perspectives on the \"center\" of a dataset. The choice of which measure to use depends on \n",
    "#the characteristics of the data and the specific goals of your analysis. It's important to consider\n",
    "#the distribution of the data, the presence of outliers, and the nature of the variables when deciding \n",
    "#which measure is most appropriate."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "026ee12c-a5df-468e-84ef-52296abf19bd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Mean: 177.01875\n",
      "Median: 177.0\n",
      "Mode: 178\n"
     ]
    }
   ],
   "source": [
    "#Question.3 Measure the three measures of central tendency for the given height data:\n",
    "#[178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]\n",
    "#Answer.3 : \n",
    "from statistics import mean, median, mode\n",
    "\n",
    "data = [178, 177, 176, 177, 178.2, 178, 175, 179, 180, 175, 178.9, 176.2, 177, 172.5, 178, 176.5]\n",
    "\n",
    "data_mean = mean(data)\n",
    "data_median = median(data)\n",
    "data_mode = mode(data)\n",
    "\n",
    "print(\"Mean:\", data_mean)\n",
    "print(\"Median:\", data_median)\n",
    "print(\"Mode:\", data_mode)\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "fda9a14b-05fc-48ef-97a4-c2f27f91d435",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Standard Deviation: 1.7885814036548633\n"
     ]
    }
   ],
   "source": [
    "#Question.4 Find the standard deviation for the given data:\n",
    "#[178,177,176,177,178.2,178,175,179,180,175,178.9,176.2,177,172.5,178,176.5]\n",
    "#Answer.4 :\n",
    "import numpy as np\n",
    "\n",
    "data = [178, 177, 176, 177, 178.2, 178, 175, 179, 180, 175, 178.9, 176.2, 177, 172.5, 178, 176.5]\n",
    "\n",
    "std_deviation = np.std(data)\n",
    "\n",
    "print(\"Standard Deviation:\", std_deviation)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "017ad0e2-4ba5-4108-bd05-96d26fd8212f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.5 How are measures of dispersion such as range, variance, and standard deviation used to describe\n",
    "#the spread of a dataset? Provide an example.\n",
    "#Answer.5 : \n",
    "#Measures of dispersion, such as range, variance, and standard deviation, are used to describe the \n",
    "#spread or variability of a dataset. They provide information about how much the values in a dataset \n",
    "#deviate from the central tendency (mean, median, etc.). These measures help us understand the \n",
    "#extent to which the data points are scattered or clustered around the central value.\n",
    "\n",
    "#Let's take an example to illustrate how these measures are used:\n",
    "\n",
    "#Suppose we have the following dataset representing the ages of a group of individuals (in years):\n",
    "\n",
    "#[28, 30, 32, 31, 29, 30, 27, 35, 28, 40]\n",
    "\n",
    "#Range:\n",
    "#The range is the simplest measure of dispersion. It's the difference between the maximum and \n",
    "#minimum values in the dataset.\n",
    "#Range = Max Value - Min Value\n",
    "#Range = 40 - 27 = 13\n",
    "\n",
    "#Variance:\n",
    "#Variance measures the average squared deviation of each data point from the mean. It gives \n",
    "#an idea of how much the data points spread out from the mean.\n",
    "#First, calculate the mean:\n",
    "#Mean = (28 + 30 + 32 + 31 + 29 + 30 + 27 + 35 + 28 + 40) / 10 = 31\n",
    "#Now calculate the squared deviations from the mean and find their average:\n",
    "#Variance = [(28 - 31)^2 + (30 - 31)^2 + ... + (40 - 31)^2] / 10\n",
    "#Variance ≈ 25.8\n",
    "\n",
    "#Standard Deviation:\n",
    "#The standard deviation is the square root of the variance. It provides a more interpretable\n",
    "#measure of dispersion in the original units of the data.\n",
    "#Standard Deviation = √Variance\n",
    "#Standard Deviation ≈ √25.8 ≈ 5.08\n",
    "\n",
    "#In this example:\n",
    "\n",
    "#Range = 13\n",
    "#Variance ≈ 25.8\n",
    "#Standard Deviation ≈ 5.08\n",
    "#Interpretation:\n",
    "#The range of 13 indicates that the ages vary by 13 years between the oldest and youngest\n",
    "#individuals. The variance and standard deviation of approximately 25.8 and 5.08, respectively, \n",
    "#indicate that the ages deviate from the mean by about 5 years on average, giving us a sense of \n",
    "#the spread or variability of the dataset.\n",
    "\n",
    "#In summary, measures of dispersion help us quantify and describe how the data points are distributed\n",
    "#around the central tendency, providing insights into the variability within the dataset."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5e13fe37-7ba3-487b-8084-c236cf30cccf",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.6 What is a Venn diagram?\n",
    "#Answer.6 A Venn diagram is a graphical representation used to show the relationships\n",
    "#between different sets, groups, or categories of items. It consists of overlapping circles or\n",
    "#other shapes, where each circle represents a set, and the overlaps between circles represent the \n",
    "#intersections between sets. Venn diagrams are commonly used to visualize the similarities and \n",
    "#differences among different elements or concepts.\n",
    "\n",
    "#The key components of a Venn diagram include:\n",
    "\n",
    "#Circles (or other shapes): Each circle represents a set or category. The elements that belong to\n",
    "#a specific set are placed inside the corresponding circle.\n",
    "\n",
    "#Overlaps: The intersections between circles represent the elements that belong to multiple sets.\n",
    "#The size of the overlap area indicates the size of the intersection between sets.\n",
    "\n",
    "#Elements: The individual items or elements being compared are placed either within the circles\n",
    "#or outside the circles, depending on whether they belong to the sets being represented.\n",
    "\n",
    "#Venn diagrams are useful for various purposes, including:\n",
    "\n",
    "#Comparing and contrasting different groups or categories.\n",
    "#Visualizing the relationships between different concepts or ideas.\n",
    "#Illustrating logical relationships and set theory operations (union, intersection, complement, etc.).\n",
    "#Representing data and relationships in fields such as mathematics, statistics, biology, social sciences,\n",
    "#and more.\n",
    "#For example, consider a Venn diagram representing two sets: \"A\" and \"B.\" If the circles representing \n",
    "#sets A and B overlap, the overlap region will represent the elements that belong to both sets A and B.\n",
    "#If the circles do not overlap, there will be no common elements between the two sets.\n",
    "\n",
    "#Overall, Venn diagrams provide a visual and intuitive way to understand the relationships and \n",
    "#interactions between sets or categories."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "8b2aa1a7-2ae3-4bcb-8d82-d337103d207a",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Intersection (A ∩ B): {2, 6}\n",
      "Union (A ∪ B): {0, 2, 3, 4, 5, 6, 7, 8, 10}\n"
     ]
    }
   ],
   "source": [
    "#Queston.7 For the two given sets A = (2,3,4,5,6,7) & B = (0,2,6,8,10). Find:\n",
    "#(i) A B\n",
    "#(ii) A ⋃ B\n",
    "#Answer.7 : \n",
    "# Given sets A and B\n",
    "A = {2, 3, 4, 5, 6, 7}\n",
    "B = {0, 2, 6, 8, 10}\n",
    "\n",
    "# Calculate the intersection (A ∩ B)\n",
    "intersection = A.intersection(B)\n",
    "print(\"Intersection (A ∩ B):\", intersection)\n",
    "\n",
    "# Calculate the union (A ∪ B)\n",
    "union = A.union(B)\n",
    "print(\"Union (A ∪ B):\", union)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5c9f73d6-9a93-4445-8532-7280dd9a4c55",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.8 What do you understand about skewness in data?\n",
    "#Answer.8 Skewness is a statistical measure that quantifies the asymmetry or lack of \n",
    "#symmetry in the distribution of a dataset. In other words, it indicates whether the data is concentrated \n",
    "#more on one side of the mean compared to the other side. Skewness provides insights into the shape\n",
    "#of the distribution and the relative frequency of extreme values.\n",
    "\n",
    "#There are three main types of skewness:\n",
    "\n",
    "#Positive Skewness (Right Skewness):\n",
    "\n",
    "#In a positively skewed distribution, the tail on the right side of the distribution is longer than\n",
    "#the left side.\n",
    "#This means that the majority of the data points are clustered to the left of the mean, while the \n",
    "#right tail is stretched out due to a few very high values.\n",
    "#The mean is typically greater than the median in a positively skewed distribution.\n",
    "#Negative Skewness (Left Skewness):\n",
    "\n",
    "#In a negatively skewed distribution, the tail on the left side of the distribution is longer than \n",
    "#the right side.\n",
    "#This implies that most of the data points are concentrated to the right of the mean, while the left\n",
    "#tail is extended by a few very low values.\n",
    "#The mean is typically less than the median in a negatively skewed distribution.\n",
    "#No Skew (Symmetrical):\n",
    "\n",
    "#A symmetrical distribution has equal tails on both sides, and the data is evenly distributed around the mean.\n",
    "#The mean and median are roughly equal in a symmetrical distribution.\n",
    "#Skewness can be calculated using mathematical formulas or software tools. One common measure of skewness\n",
    "#is the third standardized moment (also called the Pearson's skewness coefficient). However, there are \n",
    "#other methods and indices used to quantify skewness.\n",
    "\n",
    "#Interpreting skewness is important because it helps you understand the characteristics of your data\n",
    "#distribution. For instance, if you're working with financial data and you observe positive skewness,\n",
    "#it could indicate that there are a few very high returns. Conversely, negative skewness might suggest a \n",
    "#large number of low returns.\n",
    "\n",
    "#In summary, skewness provides valuable information about the shape, symmetry, and distribution of\n",
    "#data, helping analysts and researchers make informed decisions about data analysis and modeling."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b9c0cd0a-64ee-40ef-a7b1-ea393b7edb21",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Queston.9 If a data is right skewed then what will be the position of median with respect to mean?\n",
    "#Answer.9 In a right-skewed distribution, the tail on the right side (the larger values) is longer,\n",
    "#and the distribution is pulled towards the right. This means that there are relatively few high \n",
    "#values that are much larger than the rest of the data points.\n",
    "\n",
    "#In terms of the position of the median and mean:\n",
    "\n",
    "#Median: The median is less affected by extreme values or outliers compared to the mean. In a right-skewed\n",
    "#distribution, the median will generally be closer to the left side of the distribution, where\n",
    "#the majority of the data is concentrated. This is because the few very high values in the right \n",
    "#tail have less influence on the median.\n",
    "\n",
    "#Mean: The mean is influenced by all data points and is particularly sensitive to outliers. In \n",
    "#a right-skewed distribution, the mean will be pulled to the right due to the presence of the \n",
    "#few larger values in the tail. As a result, the mean will be greater than the median.\n",
    "\n",
    "#In summary, in a right-skewed distribution:\n",
    "\n",
    "#The median is typically closer to the left side (smaller values) of the distribution.\n",
    "#The mean is shifted towards the right (larger values) due to the influence of the right tail.\n",
    "#Remember that this is a general tendency and may not always hold true for every specific\n",
    "#dataset. The relationship between the mean and median can provide insights into the shape \n",
    "#and characteristics of the distribution."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c03d6f59-1d3a-4f58-a13e-c144f1fcb73a",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.10 Explain the difference between covariance and correlation. How are these measures used in\n",
    "#statistical analysis?\n",
    "#Answer.10 Covariance and correlation are both measures used in statistical analysis to quantify the\n",
    "#relationship between two variables. They provide insights into how changes in one variable are \n",
    "#related to changes in another variable. However, they differ in terms of their interpretation, \n",
    "#scale, and properties.\n",
    "\n",
    "#Covariance:\n",
    "#Covariance measures the degree to which two variables change together. A positive covariance \n",
    "#indicates that as one variable increases, the other variable tends to increase as well, and \n",
    "#vice versa. A negative covariance indicates that as one variable increases, the other variable\n",
    "#tends to decrease.\n",
    "\n",
    "\n",
    "#Correlation:\n",
    "#Correlation is a standardized measure that expresses the strength and direction of the linear\n",
    "#relationship between two variables. Unlike covariance, correlation is unitless and falls within the\n",
    "#range of -1 to 1. A correlation of +1 indicates a perfect positive linear relationship, -1 indicates a\n",
    "#perfect negative linear relationship, and 0 indicates no linear relationship.\n",
    "\n",
    "#Use in Statistical Analysis:\n",
    "\n",
    "#Covariance: Covariance is used to understand the direction of the relationship between two variables \n",
    "#and whether they tend to move together or in opposite directions. However, it doesn't provide a \n",
    "#clear indication of the strength or degree of the relationship, and its value can be difficult to \n",
    "#interpret due to its scale dependence.\n",
    "\n",
    "#Correlation: Correlation provides a standardized measure that not only indicates the direction of the\n",
    "#relationship but also quantifies the strength and degree of the linear association between \n",
    "#two variables. Correlation is widely used in statistical analysis to assess the strength of \n",
    "#relationships, identify patterns, and make predictions. It is also useful in identifying \n",
    "#multicollinearity in regression analysis.\n",
    "\n",
    "#In summary, covariance and correlation are both valuable tools for understanding the \n",
    "#relationship between variables, with correlation offering a standardized measure that\n",
    "#is often preferred for its ease of interpretation and scale independence."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a828fc1d-38ae-4fe4-ac5b-586213830ac1",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sample Mean: 69.0\n"
     ]
    }
   ],
   "source": [
    "#Question.11 What is the formula for calculating the sample mean? Provide an example calculation for a\n",
    "#dataset.\n",
    "#Answer.11  The sample mean formula is written as : \n",
    "#Sample Mean = (Sum of terms) / (Number of terms) = (∑xi)/n = (x1 + x2 + x3 ......xn)/n\n",
    "#where , \n",
    "# (∑xi) = sum of terms \n",
    "#n = number of terms \n",
    "\n",
    "#Example : Find the sample mean of 60, 57, 109, 50.\n",
    "\n",
    "#Solution in math : \n",
    "\n",
    "#To find: Sample mean\n",
    "#Sum of terms = 60 + 57 + 109 + 50 = 276\n",
    "#Number of terms = 4\n",
    "#Using sample mean formula,\n",
    "#mean = (sum of terms)/(number of terms)\n",
    "#mean = 276/4 = 69\n",
    "\n",
    "#Answer: The sample mean of 60, 57, 109, 50 is  69.\n",
    "\n",
    "#Solution with python : \n",
    "data = [60, 57, 109, 50]\n",
    "sample_mean = sum(data) / len(data)\n",
    "print(\"Sample Mean:\", sample_mean)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ac76ead2-8b3e-4b63-add3-87f5a45b1302",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.12 For a normal distribution data what is the relationship between its measure of central tendency?\n",
    "#Answer.12 In mathematical terms, for a symmetric normal distribution:\n",
    "#Mean = Median = Mode\n",
    "#This relationship is a defining characteristic of the normal distribution's symmetry.\n",
    "# in a perfectly symmetric normal distribution, the mean, median, and mode are all equal and located \n",
    "#at the center of the distribution, forming a balanced and symmetric shape."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d91737a2-d1a6-41f5-b98b-40e852031b98",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.13 How is covariance different from correlation?\n",
    "#Answer.13 Covariance:\n",
    "\n",
    "#Interpretation: Covariance measures the degree and direction of the linear relationship \n",
    "#between two variables. A positive covariance indicates that as one variable increases,\n",
    "#the other tends to increase as well, and vice versa. A negative covariance indicates an\n",
    "#inverse relationship.\n",
    "\n",
    "#Scale: The scale of covariance is not standardized and depends on the units of the variables\n",
    "#being measured. This makes it difficult to compare covariances across different datasets or \n",
    "#variables with different units.\n",
    "\n",
    "#Range: Covariance can take any real value, including positive and negative values.\n",
    "\n",
    "#Units: The units of covariance are the product of the units of the two variables (e.g., if one \n",
    "#variable is in meters and the other in kilograms, the covariance will be in meter-kilograms).\n",
    "\n",
    "#Strength: Covariance does not provide a clear indication of the strength of the relationship.\n",
    "\n",
    "#Correlation:\n",
    "\n",
    "#Interpretation: Correlation measures the strength, direction, and degree of the linear relationship\n",
    "#between two variables. It standardizes the relationship, making it unitless and comparable across \n",
    "#different datasets.\n",
    "#Scale: The scale of correlation is always between -1 and 1. A correlation of +1 indicates a perfect\n",
    "#positive linear relationship, -1 indicates a perfect negative linear relationship, and 0 indicates\n",
    "#no linear relationship.\n",
    "#Range: Correlation is always between -1 and 1.\n",
    "#Units: Correlation is unitless and does not have any units, making it easier to interpret and compare.\n",
    "#Strength: Correlation provides a clear indication of the strength of the linear relationship,\n",
    "#with 0 indicating no linear relationship and values closer to -1 or 1 indicating stronger relationships.\n",
    "\n",
    "#In summary, covariance measures the direction of the linear relationship between two variables,\n",
    "#while correlation additionally standardizes the strength of the relationship, making it easier \n",
    "#to interpret and compare. Correlation is preferred in many cases because it provides a more meaningful\n",
    "#and standardized measure of the relationship between variables, especially when comparing different\n",
    "#datasets or variables with different units."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "2fb0b75b-ba53-4d73-a84f-149d77041814",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Without Outlier:\n",
      "Mean: 65.0\n",
      "Median: 65\n",
      "Mode: None\n",
      "\n",
      "With Outlier:\n",
      "Mean: 69.58333333333333\n",
      "Median: 67.5\n",
      "Mode: None\n"
     ]
    }
   ],
   "source": [
    "#Question.14 How do outliers affect measures of central tendency and dispersion? Provide an example.\n",
    "#Answer.14 Outliers can have a significant impact on measures of central tendency (mean, median, mode)\n",
    "#and measures of dispersion (range, variance, standard deviation) in a dataset. They can distort the\n",
    "#typical pattern of the data distribution and affect the accuracy of summary statistics. Here's how \n",
    "#outliers can affect these measures, along with an example:\n",
    "\n",
    "#Measures of Central Tendency:\n",
    "\n",
    "#Mean: Outliers can disproportionately pull the mean towards their extreme values. If there are\n",
    "#high outliers, the mean will be shifted upwards, and if there are low outliers, the mean will be \n",
    "#pulled downwards.\n",
    "\n",
    "#Median: The median is less affected by outliers compared to the mean. Outliers have minimal impact\n",
    "#on the median's position, as it only considers the middle value(s) of the dataset after it is sorted.\n",
    "\n",
    "#Mode: The mode is not particularly sensitive to outliers, especially in datasets with continuous values.\n",
    "#However, if an outlier significantly deviates from the rest of the data, it might create a new mode.\n",
    "\n",
    "#Measures of Dispersion:\n",
    "\n",
    "#Range: Outliers can substantially increase the range by introducing larger or smaller values. The range\n",
    "\n",
    "#becomes an unreliable measure of spread when extreme values are present.\n",
    "\n",
    "#Variance and Standard Deviation: Outliers can greatly influence the variance and standard deviation,\n",
    "#as these measures involve the squared differences from the mean. Outliers with large deviations can \n",
    "#inflate these measures.\n",
    "\n",
    "#Example:\n",
    "\n",
    "#Consider the following dataset representing salaries (in thousands of dollars) in a company:\n",
    "\n",
    "#[40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 120]\n",
    "\n",
    "#Without the outlier (120):\n",
    "\n",
    "#Mean: (40 + 45 + 50 + 55 + 60 + 65 + 70 + 75 + 80 + 85 + 90) / 11 ≈ 68.64\n",
    "#Median: 65\n",
    "#Mode: No mode\n",
    "#With the outlier (120):\n",
    "\n",
    "#Mean: (40 + 45 + 50 + 55 + 60 + 65 + 70 + 75 + 80 + 85 + 90 + 120) / 12 ≈ 73.17\n",
    "#Median: 67.5\n",
    "#Mode: No mode\n",
    "#You can observe how the presence of an outlier (120) has influenced both the mean and the median,\n",
    "#moving them away from the center of the data distribution. The mean is particularly affected, \n",
    "#while the median is more robust to this extreme value.\n",
    "\n",
    "#example using python : \n",
    "\n",
    "data_without_outlier = [40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90]\n",
    "data_with_outlier = [40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 120]\n",
    "\n",
    "def calculate_statistics(data):\n",
    "    mean = sum(data) / len(data)\n",
    "    median = sorted(data)[len(data) // 2] if len(data) % 2 == 1 else (data[len(data) // 2 - 1] + data[len(data) // 2]) / 2\n",
    "    mode = max(set(data), key=data.count) if data.count(max(set(data), key=data.count)) > 1 else None\n",
    "    return mean, median, mode\n",
    "\n",
    "mean_without_outlier, median_without_outlier, mode_without_outlier = calculate_statistics(data_without_outlier)\n",
    "mean_with_outlier, median_with_outlier, mode_with_outlier = calculate_statistics(data_with_outlier)\n",
    "\n",
    "print(\"Without Outlier:\")\n",
    "print(\"Mean:\", mean_without_outlier)\n",
    "print(\"Median:\", median_without_outlier)\n",
    "print(\"Mode:\", mode_without_outlier)\n",
    "\n",
    "print(\"\\nWith Outlier:\")\n",
    "print(\"Mean:\", mean_with_outlier)\n",
    "print(\"Median:\", median_with_outlier)\n",
    "print(\"Mode:\", mode_with_outlier)\n",
    "\n",
    "\n",
    "#In summary, outliers can skew measures of central tendency and dispersion, emphasizing the \n",
    "#importance of assessing the impact of outliers on your analysis and potentially using robust\n",
    "#measures if the data contains significant outliers.\n",
    "\n",
    "\n",
    "\n",
    "\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
