{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "652bb88f-8d59-4047-b2f4-9dd547d51dde",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Statistics advance 1 , assignment 1 \n",
    "#Question.1 What is the Probability density function?\n",
    "#Answer.1 A Probability Density Function (PDF) is a fundamental concept\n",
    "#in probability and statistics. It describes the likelihood of a continuous\n",
    "#random variable taking on a particular value or falling within a certain range\n",
    "#of values. Unlike discrete random variables, which can take on only specific\n",
    "#values (like the outcomes of rolling a die), continuous random variables can\n",
    "#take on any value within a range (like the height of a person).\n",
    "\n",
    "#mathematically, for a continuous random variable X, the probability density \n",
    "#function f(x) is defined such that the probability of X falling within a certain\n",
    "#interval [a, b] is given by the integral of the PDF over that interval:\n",
    "\n",
    "#(a ≤ X ≤ b) = ∫[a, b] f(x) dx\n",
    "\n",
    "# PDF must satisfy two properties:\n",
    "\n",
    "#non-negativity: f(x) ≥ 0 for all x.\n",
    "#total area under the curve equals 1: ∫(-∞, ∞) f(x) dx = 1.\n",
    "\n",
    "#In other words, the PDF provides a way to represent the distribution of probabilities for a\n",
    "#continuous random variable across its entire range.\n",
    "\n",
    "#For example, consider a normal distribution. The bell-shaped curve of a normal distribution \n",
    "#is described by its PDF, and different values of the parameters (mean and standard deviation) \n",
    "#will result in different PDFs, representing different probabilities of observing various values.\n",
    "\n",
    "#It's important to note that while the PDF gives the relative likelihood of different outcomes, \n",
    "#it does not directly give the probability of a single point. The probability of a continuous\n",
    "#random variable taking on any specific value is actually zero, because the number of possible\n",
    "#values is infinite. Instead, we focus on the probabilities of intervals.\n",
    "\n",
    "#In summary, a Probability Density Function is a mathematical function that characterizes the\n",
    "#distribution of probabilities for a continuous random variable, helping us understand the\n",
    "#likelihood of various outcomes or ranges of outcomes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f1b0f7ce-a6fc-4654-9546-b0168d18eb51",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.2 What are the types of Probability distribution?\n",
    "#Answer.2 There are several types of probability distributions, each\n",
    "#dscribing the likelihood of different kinds of random variables and \n",
    "#their possibles. These distributions are essential in probability \n",
    "#theory and statistics for modeling and analyzing various real-world phenomena. Here\n",
    "#are some of the most common types of probability distributions:\n",
    "\n",
    "#Discrete Distributions:\n",
    "\n",
    "#Bernoulli Distribution: Models a binary outcome (success/failure) with a single \n",
    "#parameter representing the probability of success.\n",
    "#Binomial Distribution: Describes the number of successes in a fixed number of\n",
    "#independent Bernoulli trials.\n",
    "#Poisson Distribution: Models the number of events occurring in a fixed interval \n",
    "#of time or space, assuming a rare occurrence and constant rate.\n",
    "#Geometric Distribution: Represents the number of trials needed for the first \n",
    "#success in a sequence of independent Bernoulli trials.\n",
    "\n",
    "#Continuous Distributions:\n",
    "\n",
    "#Uniform Distribution: Equally likely outcomes over a specified interval, often depicted as a flat\n",
    "#horizontal line.\n",
    "#Normal (Gaussian) Distribution: Characterized by its bell-shaped curve, this is one of the\n",
    "#most common distributions in nature due to the Central Limit Theorem.\n",
    "#Exponential Distribution: Models the time between events in a Poisson process, such as the\n",
    "#time between phone calls at a call center.\n",
    "#Gamma Distribution: Generalizes the exponential distribution and is often used to\n",
    "#model waiting times and lifetimes.\n",
    "#Beta Distribution: Describes random variables that have values within a fixed interval, \n",
    "#commonly used in Bayesian statistics.\n",
    "#Chi-Squared Distribution: Arises in the context of the sum of squares of independent\n",
    "#standard normal random variables, commonly used in hypothesis testing and confidence intervals.\n",
    "#Cauchy Distribution: Known for its heavy tails, making it sensitive to outliers and \n",
    "#commonly used in robust statistics.\n",
    "#Log-Normal Distribution: Results from exponentiating a normally distributed random\n",
    "#variable and is often used to model quantities that are always positive (e.g., stock prices).\n",
    "\n",
    "#Multivariate Distributions:\n",
    "\n",
    "#Multinomial Distribution: Generalizes the binomial distribution to more than two outcomes.\n",
    "#Multivariate Normal Distribution: Generalizes the normal distribution to multiple dimensions,\n",
    "#commonly used in multivariate statistics.\n",
    "\n",
    "#Other Distributions:\n",
    "\n",
    "#Student's t-Distribution: Used for making inferences about the population mean when the sample\n",
    "#size is small or the population standard deviation is unknown.\n",
    "#F-Distribution: Used in ANOVA and other statistical tests to compare variances of multiple groups.\n",
    "#Weibull Distribution: Commonly used to model lifetimes of objects, including reliability analysis.\n",
    "#These are just a few examples of the many probability distributions that exist. Each distribution\n",
    "#serves a specific purpose and is used to model different types of random variables and phenomena\n",
    "#in various fields, including science, engineering, finance, and social sciences."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "65ab2b12-a7c9-4f17-8570-bd31b6e6d4ef",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "PDF at x = 1.5: 0.12951759566589174\n"
     ]
    }
   ],
   "source": [
    "#Question.3 Write a Python function to calculate the probability density function of a normal\n",
    "#istribution with given and standard deviation at a given point.\n",
    "#Answer.3 : \n",
    "import scipy.stats as stats\n",
    "\n",
    "def normal_pdf(mean, std_dev, x):\n",
    "    \"\"\"\n",
    "    Calculate the Probability Density Function (PDF) of a normal distribution\n",
    "    at a given point x, with the given mean and standard deviation.\n",
    "    \n",
    "    Args:\n",
    "        mean (float): Mean of the normal distribution.\n",
    "        std_dev (float): Standard deviation of the normal distribution.\n",
    "        x (float): Point at which to calculate the PDF.\n",
    "    \n",
    "    Returns:\n",
    "        float: Probability Density Function value at the given point x.\n",
    "    \"\"\"\n",
    "    pdf_value = stats.norm.pdf(x, loc=mean, scale=std_dev)\n",
    "    return pdf_value\n",
    "\n",
    "# Example usage\n",
    "mean = 0\n",
    "std_dev = 1\n",
    "x_value = 1.5\n",
    "pdf_at_x = normal_pdf(mean, std_dev, x_value)\n",
    "print(f\"PDF at x = {x_value}: {pdf_at_x}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "168cfed5-7505-4b24-8e20-3bc50268845f",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.4 What are the properties of Binomial distribution? Give two examples of events where binomial\n",
    "#distribution can be applied.\n",
    "#Answer.4 he binomial distribution is a fundamental probability distribution that describes\n",
    "#the number of successes in a fixed number of independent Bernoulli trials (binary outcomes:\n",
    "#success or failure) with the same probability of success in each trial. The properties\n",
    "#of the binomial distribution include:\n",
    "\n",
    "#Parameters:\n",
    "\n",
    "#n: Number of trials.\n",
    "#p: Probability of success on each trial.\n",
    "#Probability Mass Function (PMF):\n",
    "#The probability of getting exactly k successes in n trials is given by:\n",
    "#P(X = k) = (n choose k) * p^k * (1 - p)^(n - k)\n",
    "#where \"n choose k\" represents the binomial coefficient.\n",
    "\n",
    "#Mean and Variance:\n",
    "    \n",
    "#Mean (μ) = n * p\n",
    "#Variance (σ^2) = n * p * (1 - p)\n",
    "\n",
    "#Shape:\n",
    "#The shape of the binomial distribution is influenced by n (number of trials) and p \n",
    "#(probability of success). As n increases while keeping p fixed, the distribution becomes \n",
    "#more symmetric and approaches a normal distribution.\n",
    "\n",
    "#Use of the Cumulative Distribution Function (CDF):\n",
    "#The cumulative distribution function gives the probability that the number of\n",
    "#successes is less than or equal to a certain value.\n",
    "\n",
    "#Two examples of events where the binomial distribution can be applied are:\n",
    "\n",
    "#Coin Flipping:\n",
    "#Suppose you flip a fair coin (with a 50% chance of heads and 50% chance of tails)\n",
    "#10 times. You can model the number of times you get heads as a binomial distribution \n",
    "#with parameters n = 10 and p = 0.5.\n",
    "\n",
    "#Quality Control:\n",
    "    \n",
    "#A manufacturing process produces items, and each item can be either defective (failure)\n",
    "#or non-defective (success). Let's say you're interested in the number of defective items \n",
    "#in a sample of 50 items produced by this process. You could model this using a binomial\n",
    "#distribution with parameters n = 50 and a given probability p of an item being defective\n",
    "#based on historical data.\n",
    "\n",
    "#In both examples, the binomial distribution helps you analyze and predict the\n",
    "#likelihood of getting a certain number of successes (e.g., heads, defective items)\n",
    "#in a fixed number of trials or observations."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "7eef82f1-a96a-4fcd-8244-8712a7557d8c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAkkAAAHFCAYAAADmGm0KAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjYuMiwgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy8o6BhiAAAACXBIWXMAAA9hAAAPYQGoP6dpAABT3UlEQVR4nO3de1xUdf4/8NfIZUAUVORqXHVVFLxBKRiiKZDXNNtVM9QUW0JTGTUF9OslEzXXSAVZXQzNvPxKbatlk/GaLWgKeEnN3BbFC0TgBZOCAT6/P3xwcpzDbRxmNF/Px4OHzOd8zufzOW8GfXnOmRmFEEKAiIiIiLQ0M/UCiIiIiB5HDElEREREMhiSiIiIiGQwJBERERHJYEgiIiIiksGQRERERCSDIYmIiIhIBkMSERERkQyGJCIiIiIZDEn0h5aWlgaFQoGTJ0/Kbh82bBg8PT212jw9PTFp0qRGzZOZmYnFixfj9u3b+i30KbRr1y507doV1tbWUCgUOHXqlGy/w4cPQ6FQaH21bt0avXv3xpYtW3T66/PzM7aaYzp8+HCT7ftw3SwtLeHg4IC+ffsiPj4eV65c0dmn5vfl8uXLjVrT8uXL8dlnnzVqH7m5+vfvD19f30aNU5/09HQsXrxYdtuT8Fwh0zI39QKIHjd79+6Fra1to/bJzMzEkiVLMGnSJLRq1appFvYH8vPPPyMiIgIvvvgikpOToVQq0bFjxzr3Wb58OQYMGAAAKC4uxtatWzFp0iSUlpbirbfekvrp8/Mztl69eiErKwtdunRp8rlq6lZVVYWSkhIcP34cmzdvxvvvv49NmzZh/PjxUt+hQ4ciKysLLi4ujZ7jlVdewciRIxu8j75zNVZ6ejqSkpJkg9KT8Fwh02JIInpIz549Tb2ERtNoNFAoFDA3fzJ+pX/44QdoNBq89tprCAkJadA+f/rTn9CnTx/p8ZAhQ3DixAns2LFDKyQ9CT8/W1tbrWNpSg/XbcSIEZg9ezYGDRqESZMmoVu3bvDz8wMAODg4wMHBoUnX8+uvv8LKysooc9XnSXiukGnxchvRQx4+BV9dXY1ly5ahU6dOsLa2RqtWrdCtWzd88MEHAIDFixdj7ty5AAAvLy/p8kbN5ZDq6mqsWrUKnTt3hlKphKOjIyZMmIBr165pzSuEwPLly+Hh4QErKysEBARArVajf//+6N+/v9Sv5jLKRx99hNmzZ6Ndu3ZQKpX473//i59//hnR0dHo0qULWrRoAUdHR7zwwgs4evSo1lyXL1+GQqHAe++9h5UrV8LT0xPW1tbo37+/FGDmz58PV1dX2NnZYdSoUSgqKmpQ/T7//HMEBgaiefPmaNmyJUJDQ5GVlSVtnzRpEp5//nkAwJgxY6BQKLSOr6GaNWuGFi1awMLCQqv94Z9fTb127NiB+Ph4uLq6wtbWFoMGDcLFixd1xt28eTO6d+8OKysrtGnTBqNGjcKFCxe0+kyaNAktWrTA999/j/DwcNjY2MDFxQUrVqwAABw7dgzPP/88bGxs0LFjR53LgnKXzE6ePImxY8dKPwtPT0+MGzdO9rLYo2rTpg3+/ve/o7KyEu+//77ULncJLDc3F8OGDYOjoyOUSiVcXV0xdOhQ6fmrUChw7949bNmyRXru1/w8a8bLyMjA5MmT4eDggObNm6O8vLzOS3tHjx5Fnz59YG1tjXbt2mHhwoWoqqqSttd2ybHmeZ2Wlgbg/s8pKSlJWmfNV82ccpfb8vPz8dprr0nH6+Pjg7/97W+orq7WmWf16tVYs2YNvLy80KJFCwQGBuLYsWON+EnQ4+7J+G8n0SOqqqpCZWWlTrsQot59V61ahcWLF2PBggXo168fNBoNvv/+e+n+o8jISNy8eRPr1q3Dnj17pMsHNZdS3nzzTWzcuBHTp0/HsGHDcPnyZSxcuBCHDx9GTk4O2rZtCwCIj49HQkIC3njjDbz88su4evUqIiMjodFoZC9FxcbGIjAwECkpKWjWrBkcHR3x888/AwAWLVoEZ2dn/PLLL9i7dy/69++PAwcO6ISRpKQkdOvWDUlJSbh9+zZmz56N4cOHo3fv3rCwsMDmzZtx5coVzJkzB5GRkfj888/rrNX27dsxfvx4hIWFYceOHSgvL8eqVauk+Z9//nksXLgQzz33HKZNmyZdCmrIJY/q6mrpZ1hSUoIPP/wQ3333HTZu3FjvvgAQFxeHvn374h//+AdKS0sxb948DB8+HBcuXICZmRkAICEhAXFxcRg3bhwSEhJQUlKCxYsXIzAwECdOnMCf/vQnaTyNRoOXX34ZUVFRmDt3LrZv347Y2FiUlpZi9+7dmDdvHp555hmsW7cOkyZNgq+vL/z9/Wtd3+XLl9GpUyeMHTsWbdq0QUFBATZs2IBnn30W58+fl54nhvLss8/CxcUFX3/9da197t27h9DQUHh5eSEpKQlOTk4oLCzEoUOHcPfuXQBAVlYWXnjhBQwYMAALFy4EAJ2f5+TJkzF06FB89NFHuHfvnk6wfVBhYSHGjh2L+fPnY+nSpfjXv/6FZcuW4datW1i/fn2jjnHhwoW4d+8ePv30U62gXtslvp9//hlBQUGoqKjAO++8A09PT3z55ZeYM2cOfvzxRyQnJ2v1T0pKQufOnZGYmCjNN2TIEOTl5cHOzq5Ra6XHlCD6A/vwww8FgDq/PDw8tPbx8PAQEydOlB4PGzZM9OjRo8553nvvPQFA5OXlabVfuHBBABDR0dFa7cePHxcARFxcnBBCiJs3bwqlUinGjBmj1S8rK0sAECEhIVLboUOHBADRr1+/eo+/srJSaDQaMXDgQDFq1CipPS8vTwAQ3bt3F1VVVVJ7YmKiACBGjBihNc6sWbMEAHHnzp1a56qqqhKurq7Cz89Pa8y7d+8KR0dHERQUpHMMn3zySb3HUNP34a9mzZqJ+Ph4nf4P//xq9h8yZIhWv//3//6fACCysrKEEELcunVLWFtb6/TLz88XSqVSvPrqq1LbxIkTBQCxe/duqU2j0QgHBwcBQOTk5EjtJSUlwszMTKhUKp01HTp0qNbjrqysFL/88ouwsbERH3zwQaP2fbBfXTXu3bu3sLa2lh7X/L7UPI9PnjwpAIjPPvuszrlsbGy0av7weBMmTKh124O/MyEhIQKA+Oc//6nVd+rUqaJZs2biypUrWsf2cA1qntcffvih1DZt2jRR2z91Dz9X5s+fLwCI48ePa/V78803hUKhEBcvXtSax8/PT1RWVkr9vv32WwFA7NixQ3Y+evLwchs9FbZu3YoTJ07ofNVc9qnLc889h9OnTyM6Ohr79u1DaWlpg+c9dOgQAOic0n/uuefg4+ODAwcOALh/eaa8vBx/+ctftPr16dNH59V3NUaPHi3bnpKSgl69esHKygrm5uawsLDAgQMHdC4ZAffv62nW7Pe/Bnx8fADcv6n2QTXt+fn5tRwpcPHiRdy4cQMRERFaY7Zo0QKjR4/GsWPHUFZWVuv+9Vm5cqX0c1Or1Xj77bexYsUK6VJnfUaMGKH1uFu3bgAgXc7KysrCr7/+qvOzcnNzwwsvvCD9rGooFAoMGTJEemxubo4OHTrAxcVF616XNm3awNHRsd7LZr/88gvmzZuHDh06wNzcHObm5mjRogXu3bsn+7MzBFHPmdQOHTqgdevWmDdvHlJSUnD+/Hm95qntuSqnZcuWOj+rV199FdXV1XWe9TKEgwcPokuXLnjuuee02idNmgQhBA4ePKjVPnToUOksJKD7nKInHy+30VPBx8cHAQEBOu12dna4evVqnfvGxsbCxsYG27ZtQ0pKCszMzNCvXz+sXLlSdswHlZSUAJA/ve/q6ir9ZVrTz8nJSaefXFttY65ZswazZ89GVFQU3nnnHbRt2xZmZmZYuHCh7D+0bdq00XpsaWlZZ/tvv/0mu5YHj6G2Y62ursatW7fQvHnzWseoi7e3t1a9Bw0ahFu3buFvf/sbpkyZgs6dO9e5v729vdZjpVIJ4P6NxA1Zv1qt1mpr3rw5rKystNosLS11alfTXlftgPtB4MCBA1i4cCGeffZZ2NraSkGsZo2Glp+fD1dX11q329nZ4ciRI3j33XcRFxeHW7duwcXFBVOnTsWCBQvqvGz2oMa8gk3u+e7s7Azg959RUykpKZH9T0lNjR6ev77nFD35GJKI6mFubg6VSgWVSoXbt29j//79iIuLQ3h4OK5evVrnP/o1f4kWFBTgmWee0dp248YN6T6Tmn4//fSTzhiFhYWyf3ErFAqdtm3btqF///7YsGGDVnvN/SNN6cFjfdiNGzfQrFkztG7d2qBzduvWDUIInDlzpt6QVJ/61m/oe4IedOfOHXz55ZdYtGgR5s+fL7WXl5fj5s2bTTLnt99+i8LCQkyZMqXOfn5+fti5c6dU57S0NCxduhTW1tZaa62L3HO1NrX9DgC//4xqwml5eblWv+Li4gbPI8fe3r7Wnz+AJn0O0OOJl9uIGqFVq1Z45ZVXMG3aNNy8eVN6lUxt/4N84YUXANwPLw86ceIELly4gIEDBwIAevfuDaVSiV27dmn1O3bsWKNO3SsUCmktNc6cOaN102pT6dSpE9q1a4ft27drXca5d+8edu/eLb3izZBq3oDS0dHxkccKDAyEtbW1zs/q2rVrOHjwoPSzagoKhQJCCJ2f3T/+8Q+tV3UZys2bNxEVFQULCwvExMQ0eI3du3fH+++/j1atWiEnJ0faplQqDXb25O7duzovENi+fTuaNWuGfv36AYD0n4YzZ85o9ZN7YUFjzu4MHDgQ58+f1zo24P7leoVCIb1PFz09eCaJqB7Dhw+Hr68vAgIC4ODggCtXriAxMREeHh7Sq51q3mfmgw8+wMSJE2FhYYFOnTqhU6dOeOONN7Bu3To0a9YMgwcPll7d5ubmJv0D1aZNG6hUKiQkJKB169YYNWoUrl27hiVLlsDFxUXrHp+6DBs2DO+88w4WLVqEkJAQXLx4EUuXLoWXl5fsq/sMqVmzZli1ahXGjx+PYcOG4a9//SvKy8vx3nvv4fbt29LL4/V16dIl6eXVd+7cwf79+5GamoqAgAAEBwc/8vpbtWqFhQsXIi4uDhMmTMC4ceNQUlKCJUuWwMrKCosWLXrkOWpja2uLfv364b333kPbtm3h6emJI0eOIDU19ZHfnLSmbtXV1dKbSaampqK0tBRbt25F165da933yy+/RHJyMkaOHAlvb28IIbBnzx7cvn0boaGhUj8/Pz8cPnwYX3zxBVxcXNCyZUt06tRJr/Xa29vjzTffRH5+Pjp27Ij09HRs2rQJb775Jtzd3QHcv/w2aNAg6ffFw8MDBw4cwJ49e3TGq/ndXLlyJQYPHgwzMzN069ZNuoT8oJiYGGzduhVDhw7F0qVL4eHhgX/9619ITk7Gm2++We8bntIfD0MSUT0GDBiA3bt3Sy8dd3Z2RmhoKBYuXCjdk9G/f3/ExsZiy5Yt2LRpE6qrq3Ho0CHp0lf79u2RmpqKpKQk2NnZ4cUXX0RCQoLWPQ3vvvsubGxskJKSgg8//BCdO3fGhg0bEB8f3+B/KOPj41FWVobU1FSsWrUKXbp0QUpKCvbu3avXR2A01quvvgobGxskJCRgzJgxMDMzQ58+fXDo0CEEBQU90thxcXHS9zY2NvDw8MDChQuhUqm0bp59FLGxsXB0dMTatWuxa9cu6b2jli9frvXy/6awfft2zJw5E2+//TYqKyvRt29fqNVqnZvoG6umbubm5rCzs0PHjh0xefJkvPHGG/Dw8Khz3z/96U9o1aoVVq1ahRs3bsDS0hKdOnVCWloaJk6cKPX74IMPMG3aNIwdOxZlZWUICQnR+/nm7OyMpKQkzJkzB2fPnkWbNm0QFxeHJUuWaPX76KOP8NZbb2HevHmoqqrC8OHDsWPHDp37BF999VX85z//QXJyMpYuXQohBPLy8mQvYTs4OCAzMxOxsbHS2zl4e3tj1apVUKlUeh0PPdkUor6XNxCRyeTl5aFz585YtGiRVkggIqKmx5BE9Jg4ffo0duzYgaCgINja2uLixYtYtWoVSktL8d1339X6KjciImoavNxG9JiwsbHByZMnkZqaitu3b8POzg79+/fHu+++y4BERGQCPJNEREREJINvAUBEREQkgyGJiIiISAZDEhEREZEM3ritp+rqaty4cQMtW7Zs1FvuExERkekIIXD37l24urrW+0a9DEl6unHjBtzc3Ey9DCIiItLD1atXdT5T82EMSXpq2bIlgPtFtrW1NejYGo0GGRkZCAsLa/CnbFPjsc7GwTobB+tsHKyzcTRlnUtLS+Hm5ib9O14XhiQ91Vxis7W1bZKQ1Lx5c9ja2vKXsAmxzsbBOhsH62wcrLNxGKPODblVhjduExEREclgSCIiIiKSwZBEREREJIMhiYiIiEgGQxIRERGRDIYkIiIiIhkMSUREREQyGJKIiIiIZDAkEREREclgSCIiIiKSYfKQlJycDC8vL1hZWcHf3x9Hjx6ts/+RI0fg7+8PKysreHt7IyUlRWv7nj17EBAQgFatWsHGxgY9evTARx99pNVn8eLFUCgUWl/Ozs4GPzYiIiJ6cpk0JO3atQuzZs1CfHw8cnNzERwcjMGDByM/P1+2f15eHoYMGYLg4GDk5uYiLi4OM2bMwO7du6U+bdq0QXx8PLKysnDmzBm8/vrreP3117Fv3z6tsbp27YqCggLp6+zZs016rERERPRkMekH3K5ZswZTpkxBZGQkACAxMRH79u3Dhg0bkJCQoNM/JSUF7u7uSExMBAD4+Pjg5MmTWL16NUaPHg0A6N+/v9Y+M2fOxJYtW/DNN98gPDxcajc3N+fZIyIiIqqVyc4kVVRUIDs7G2FhYVrtYWFhyMzMlN0nKytLp394eDhOnjwJjUaj018IgQMHDuDixYvo16+f1rZLly7B1dUVXl5eGDt2LP73v/894hERERHRH4nJziQVFxejqqoKTk5OWu1OTk4oLCyU3aewsFC2f2VlJYqLi+Hi4gIAuHPnDtq1a4fy8nKYmZkhOTkZoaGh0j69e/fG1q1b0bFjR/z0009YtmwZgoKCcO7cOdjb28vOXV5ejvLyculxaWkpAECj0cgGtEdRM56hxyVtrLNxsM7GwTobB+tsHE1Z58aMadLLbQCgUCi0HgshdNrq6/9we8uWLXHq1Cn88ssvOHDgAFQqFby9vaVLcYMHD5b6+vn5ITAwEO3bt8eWLVugUqlk501ISMCSJUt02jMyMtC8efO6D1JParW6ScYlbayzcbDOxsE6GwfrbBxNUeeysrIG9zVZSGrbti3MzMx0zhoVFRXpnC2q4ezsLNvf3Nxc6wxQs2bN0KFDBwBAjx49cOHCBSQkJOjcr1TDxsYGfn5+uHTpUq3rjY2N1QpQpaWlcHNzQ1hYGGxtbes81sbSaDRQq9UIDQ2FhYWFQcem37HOxsE6GwfrbByss3E0ZZ1rrgQ1hMlCkqWlJfz9/aFWqzFq1CipXa1W46WXXpLdJzAwEF988YVWW0ZGBgICAuosohBC61LZw8rLy3HhwgUEBwfX2kepVEKpVOq0W1hYNNkvSlOOTb9jnY2DdTYO1tk4WGfjaIo6N2Y8k15uU6lUiIiIQEBAAAIDA7Fx40bk5+cjKioKwP2zN9evX8fWrVsBAFFRUVi/fj1UKhWmTp2KrKwspKamYseOHdKYCQkJCAgIQPv27VFRUYH09HRs3boVGzZskPrMmTMHw4cPh7u7O4qKirBs2TKUlpZi4sSJxi0AERERPbZMGpLGjBmDkpISLF26FAUFBfD19UV6ejo8PDwAAAUFBVrvmeTl5YX09HTExMQgKSkJrq6uWLt2rfTyfwC4d+8eoqOjce3aNVhbW6Nz587Ytm0bxowZI/W5du0axo0bh+LiYjg4OKBPnz44duyYNC8RERGRyW/cjo6ORnR0tOy2tLQ0nbaQkBDk5OTUOt6yZcuwbNmyOufcuXNno9ZIRERETx+TfywJERER0eOIIYmIiIhIBkMSERERkQyGJCIiIiIZDElEREREMhiSiIiIiGQwJBERERHJYEgiIiIiksGQRERERCSDIYmIiIhIBkMSERERkQyGJCIiIiIZDElEREREMhiSiIiIiGQwJBERERHJYEgiIiIiksGQRERERCSDIYmIiIhIBkMSERERkQyGJCIiIiIZDElEREREMhiSiIiIiGQwJBERERHJYEgiIiIiksGQRERERCSDIYmIiIhIBkMSERERkQyGJCIiIiIZDElEREREMhiSiIiIiGQwJBERERHJYEgiIiIiksGQRERERCSDIYmIiIhIBkMSERERkQyGJCIiIiIZDElEREREMhiSiIiIiGQwJBERERHJYEgiIiIikmHykJScnAwvLy9YWVnB398fR48erbP/kSNH4O/vDysrK3h7eyMlJUVr+549exAQEIBWrVrBxsYGPXr0wEcfffTI8xIREdHTxaQhadeuXZg1axbi4+ORm5uL4OBgDB48GPn5+bL98/LyMGTIEAQHByM3NxdxcXGYMWMGdu/eLfVp06YN4uPjkZWVhTNnzuD111/H66+/jn379uk9LxERET19TBqS1qxZgylTpiAyMhI+Pj5ITEyEm5sbNmzYINs/JSUF7u7uSExMhI+PDyIjIzF58mSsXr1a6tO/f3+MGjUKPj4+aN++PWbOnIlu3brhm2++0XteIiIievqYm2riiooKZGdnY/78+VrtYWFhyMzMlN0nKysLYWFhWm3h4eFITU2FRqOBhYWF1jYhBA4ePIiLFy9i5cqVes8LAOXl5SgvL5cel5aWAgA0Gg00Gk09R9s4NeMZelzSxjobB+tsHKyzcbDOxtGUdW7MmCYLScXFxaiqqoKTk5NWu5OTEwoLC2X3KSwslO1fWVmJ4uJiuLi4AADu3LmDdu3aoby8HGZmZkhOTkZoaKje8wJAQkIClixZotOekZGB5s2b13/AelCr1U0yLmljnY2DdTYO1tk4WGfjaIo6l5WVNbivyUJSDYVCofVYCKHTVl//h9tbtmyJU6dO4ZdffsGBAwegUqng7e2N/v376z1vbGwsVCqV9Li0tBRubm4ICwuDra1t7QeoB41GA7VajdDQUJ2zY2Q4rLNxsM7GwTobB+tsHE1Z55orQQ1hspDUtm1bmJmZ6Zy9KSoq0jnLU8PZ2Vm2v7m5Oezt7aW2Zs2aoUOHDgCAHj164MKFC0hISED//v31mhcAlEollEqlTruFhUWT/aI05dj0O9bZOFhn42CdjYN1No6mqHNjxjPZjduWlpbw9/fXOZWmVqsRFBQku09gYKBO/4yMDAQEBNR50EII6X4ifeYlIiKip49JL7epVCpEREQgICAAgYGB2LhxI/Lz8xEVFQXg/iWu69evY+vWrQCAqKgorF+/HiqVClOnTkVWVhZSU1OxY8cOacyEhAQEBASgffv2qKioQHp6OrZu3ar1yrX65iUiIiIyaUgaM2YMSkpKsHTpUhQUFMDX1xfp6enw8PAAABQUFGi9d5GXlxfS09MRExODpKQkuLq6Yu3atRg9erTU5969e4iOjsa1a9dgbW2Nzp07Y9u2bRgzZkyD5yUiIiIy+Y3b0dHRiI6Olt2Wlpam0xYSEoKcnJxax1u2bBmWLVv2SPMSERERmfxjSYiIiIgeRwxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRNQkpqSd0Ho8/eMcE62EiEg/DElEREREMhiSiIiIiGQwJBERERHJYEgiIiIiksGQRERERCTD5CEpOTkZXl5esLKygr+/P44ePVpn/yNHjsDf3x9WVlbw9vZGSkqK1vZNmzYhODgYrVu3RuvWrTFo0CB8++23Wn0WL14MhUKh9eXs7GzwYyMiIqInl0lD0q5duzBr1izEx8cjNzcXwcHBGDx4MPLz82X75+XlYciQIQgODkZubi7i4uIwY8YM7N69W+pz+PBhjBs3DocOHUJWVhbc3d0RFhaG69eva43VtWtXFBQUSF9nz55t0mMlIiKiJ4u5KSdfs2YNpkyZgsjISABAYmIi9u3bhw0bNiAhIUGnf0pKCtzd3ZGYmAgA8PHxwcmTJ7F69WqMHj0aAPDxxx9r7bNp0yZ8+umnOHDgACZMmCC1m5ub8+wRERER1cpkIamiogLZ2dmYP3++VntYWBgyMzNl98nKykJYWJhWW3h4OFJTU6HRaGBhYaGzT1lZGTQaDdq0aaPVfunSJbi6ukKpVKJ3795Yvnw5vL29a11veXk5ysvLpcelpaUAAI1GA41GU/fBNlLNeIYel7Sxzk3LHNVavx81j6lp8PlsHKyzcTRlnRszpslCUnFxMaqqquDk5KTV7uTkhMLCQtl9CgsLZftXVlaiuLgYLi4uOvvMnz8f7dq1w6BBg6S23r17Y+vWrejYsSN++uknLFu2DEFBQTh37hzs7e1l505ISMCSJUt02jMyMtC8efN6j1cfarW6ScYlbaxz0xjSGkhPT5ceh7Uu0npMTYPPZ+NgnY2jKepcVlbW4L4mvdwGAAqFQuuxEEKnrb7+cu0AsGrVKuzYsQOHDx+GlZWV1D548GDpez8/PwQGBqJ9+/bYsmULVCqV7LyxsbFa20pLS+Hm5oawsDDY2trWcYSNp9FooFarERoaKnt2jAyDdW5a0z/OwfrxvaQ6Z9xyROL4AFMv6w+Lz2fjYJ2NoynrXHMlqCFMFpLatm0LMzMznbNGRUVFOmeLajg7O8v2Nzc31zkDtHr1aixfvhz79+9Ht27d6lyLjY0N/Pz8cOnSpVr7KJVKKJVKnXYLC4sm+0VpyrHpd6xz06hEM626PvyYmgafz8bBOhtHU9S5MeOZ7NVtlpaW8Pf31zmVplarERQUJLtPYGCgTv+MjAwEBARoHfR7772Hd955B1999RUCAur/n2t5eTkuXLgge7mOiIiInk4mfQsAlUqFf/zjH9i8eTMuXLiAmJgY5OfnIyoqCsD9S1wPviItKioKV65cgUqlwoULF7B582akpqZizpw5Up9Vq1ZhwYIF2Lx5Mzw9PVFYWIjCwkL88ssvUp85c+bgyJEjyMvLw/Hjx/HKK6+gtLQUEydONN7BExER0WPNpPckjRkzBiUlJVi6dCkKCgrg6+uL9PR0eHh4AAAKCgq03jPJy8sL6enpiImJQVJSElxdXbF27Vrp5f/A/TenrKiowCuvvKI116JFi7B48WIAwLVr1zBu3DgUFxfDwcEBffr0wbFjx6R5iYiIiEx+43Z0dDSio6Nlt6Wlpem0hYSEICcnp9bxLl++XO+cO3fubOjyiIiI6Cll8o8lISIiInocMSQRERERyWBIIiIiIpLBkERERjMl7QSmpJ0w9TKIiBqEIYmIiIhIBkMSERERkQyGJCIiIiIZDElEREREMhiSiIiIiGQwJBERERHJYEgiIiIiksGQRERERCSDIYmIiIhIBkMSERERkQyGJCIiIiIZDElEREREMhiSiIiIiGQwJBERERHJYEgiIiIiksGQRERERCSDIYmIiIhIBkMSERERkQyGJCIiIiIZDElE1GSmpJ0w9RKIiPTGkEREREQkgyGJiIiISIZeISktLQ1lZWWGXgsRERHRY0OvkBQbGwtnZ2dMmTIFmZmZhl4TERERkcnpFZKuXbuGbdu24datWxgwYAA6d+6MlStXorCw0NDrIyIiIjIJvUKSmZkZRowYgT179uDq1at444038PHHH8Pd3R0jRozAP//5T1RXVxt6rURERERG88g3bjs6OqJv374IDAxEs2bNcPbsWUyaNAnt27fH4cOHDbBEIiIiIuPTOyT99NNPWL16Nbp27Yr+/fujtLQUX375JfLy8nDjxg28/PLLmDhxoiHXSkRERGQ05vrsNHz4cOzbtw8dO3bE1KlTMWHCBLRp00babm1tjdmzZ+P999832EKJiIiIjEmvkOTo6IgjR44gMDCw1j4uLi7Iy8vTe2FEREREpqTX5baQkBD06tVLp72iogJbt24FACgUCnh4eDza6ojoD40fW0JEjzO9QtLrr7+OO3fu6LTfvXsXr7/++iMvioiIiMjU9ApJQggoFAqd9mvXrsHOzu6RF0VERERkao26J6lnz55QKBRQKBQYOHAgzM1/372qqgp5eXl48cUXDb5IIiIiImNrVEgaOXIkAODUqVMIDw9HixYtpG2Wlpbw9PTE6NGjDbpAIiIiIlNoVEhatGgRAMDT0xNjxoyBlZXVIy8gOTkZ7733HgoKCtC1a1ckJiYiODi41v5HjhyBSqXCuXPn4OrqirfffhtRUVHS9k2bNmHr1q347rvvAAD+/v5Yvnw5nnvuuUeal4iIiJ4uet2TNHHiRIMEpF27dmHWrFmIj49Hbm4ugoODMXjwYOTn58v2z8vLw5AhQxAcHIzc3FzExcVhxowZ2L17t9Tn8OHDGDduHA4dOoSsrCy4u7sjLCwM169f13teIiIievo0OCS1adMGxcXFAIDWrVujTZs2tX411Jo1azBlyhRERkbCx8cHiYmJcHNzw4YNG2T7p6SkwN3dHYmJifDx8UFkZCQmT56M1atXS30+/vhjREdHo0ePHujcuTM2bdqE6upqHDhwQO95iYiI6OnT4Mtt77//Plq2bCl9L/fqtsaoqKhAdnY25s+fr9UeFhaGzMxM2X2ysrIQFham1RYeHo7U1FRoNBpYWFjo7FNWVgaNRiOFN33mJSIioqdPg0PSg5/DNmnSpEeeuLi4GFVVVXByctJqd3JyQmFhoew+hYWFsv0rKytRXFwMFxcXnX3mz5+Pdu3aYdCgQXrPCwDl5eUoLy+XHpeWlgIANBoNNBpNHUfaeDXjGXpc0sY6Ny1zVAP4vb41jx9uY/0Ng89n42CdjaMp69yYMRsckmpCQUPY2to2uO/DZ6Rqew+muvrLtQPAqlWrsGPHDhw+fFjnHqrGzpuQkIAlS5botGdkZKB58+a17vco1Gp1k4xL2ljnpjGk9f0/1er7//kIa10kbUtPT5f61HxPhsHns3GwzsbRFHUuKytrcN8Gh6RWrVrVe4mtJmhUVVXVO17btm1hZmamc/amqKhI5yxPDWdnZ9n+5ubmsLe312pfvXo1li9fjv3796Nbt26PNC8AxMbGQqVSSY9LS0vh5uaGsLCwRoXChtBoNFCr1QgNDZW9hEiGwTobzvSPc7B+fC+t76d/nAMAeP8vflCr1ci45YjKB26DrOlTsx89Gj6fjYN1No6mrHNjTvo0OCQdOnRIr8XUxtLSEv7+/lCr1Rg1apTUrlar8dJLL8nuExgYiC+++EKrLSMjAwEBAVpFfO+997Bs2TLs27cPAQEBjzwvACiVSiiVSp12CwuLJvtFacqx6Xes86OrRDOphjXf1wSiB9sfDEk1fVh7w+Lz2ThYZ+Noijo3ZrwGh6SQkBC9FlMXlUqFiIgIBAQEIDAwEBs3bkR+fr70vkexsbG4fv269KG5UVFRWL9+PVQqFaZOnYqsrCykpqZix44d0pirVq3CwoULsX37dnh6ekpnjFq0aCG9+WV98xIRERE1OCSdOXMGvr6+aNasGc6cOVNn3wcvb9VlzJgxKCkpwdKlS1FQUABfX1+kp6fDw8MDAFBQUKD13kVeXl5IT09HTEwMkpKS4OrqirVr12q9y3dycjIqKirwyiuvaM21aNEiLF68uEHzEhERETU4JPXo0QOFhYVwdHREjx49oFAopJumH9TQe5JqREdHIzo6WnZbWlqaTltISAhycnJqHe/y5cuPPC8RERFRg0NSXl4eHBwcpO+JiIiI/sgaHJIevBTFy1JERET0R9eoD7h90MWLF7Fu3TpcuHABCoUCnTt3xltvvYVOnToZcn1EREREJqHXB9x++umn8PX1RXZ2Nrp3745u3bohJycHvr6++OSTTwy9RiIiIiKj0+tM0ttvv43Y2FgsXbpUq33RokWYN28e/vznPxtkcURERESmoteZpMLCQkyYMEGn/bXXXqvz88+IiIiInhR6haT+/fvj6NGjOu3ffPMNgoODH3lRRERERKbW4Mttn3/+ufT9iBEjMG/ePGRnZ6NPnz4AgGPHjuGTTz6R/RBYIiIioidNg0PSyJEjddqSk5ORnJys1TZt2jR+vAcRERE98Rockqqrq5tyHURERESPFb3uSSIiIiL6o9P7zSTv3buHI0eOID8/HxUVFVrbZsyY8cgLIyIiIjIlvUJSbm4uhgwZgrKyMty7dw9t2rRBcXExmjdvDkdHR4YkIiIieuLpdbktJiYGw4cPx82bN2FtbY1jx47hypUr8Pf3x+rVqw29RiIiIiKj0ysknTp1CrNnz4aZmRnMzMxQXl4ONzc3rFq1CnFxcYZeIxE9IaaknTD1EoiIDEavkGRhYQGFQgEAcHJyQn5+PgDAzs5O+p6IiIjoSabXPUk9e/bEyZMn0bFjRwwYMAD/93//h+LiYnz00Ufw8/Mz9BqJiIiIjE6vM0nLly+Hi4sLAOCdd96Bvb093nzzTRQVFWHjxo0GXSARERGRKeh1JikgIED63sHBAenp6QZbEBEREdHjQO/3SQKAoqIiXLx4EQqFAp06dYKDg4Oh1kVERERkUnpdbistLUVERATatWuHkJAQ9OvXD66urnjttddw584dQ6+RiIiIyOj0CkmRkZE4fvw4vvzyS9y+fRt37tzBl19+iZMnT2Lq1KmGXiMRERGR0el1ue1f//oX9u3bh+eff15qCw8Px6ZNm/Diiy8abHFEREREpqLXmSR7e3vY2dnptNvZ2aF169aPvCgiIiIiU9MrJC1YsAAqlQoFBQVSW2FhIebOnYuFCxcabHFE9OSb/nGOqZdARKSXBl9u69mzp/Qu2wBw6dIleHh4wN3dHQCQn58PpVKJn3/+GX/9618Nv1IiIiIiI2pwSBo5cmQTLoOIiIjo8dLgkLRo0aKmXAcRERHRY+WR3kwyOzsbFy5cgEKhQJcuXdCzZ09DrYuIiIjIpPQKSUVFRRg7diwOHz6MVq1aQQiBO3fuYMCAAdi5cyffeZuIiIieeHq9uu2tt95CaWkpzp07h5s3b+LWrVv47rvvUFpaihkzZhh6jURERERGp9eZpK+++gr79++Hj4+P1NalSxckJSUhLCzMYIsjIiIiMhW9ziRVV1fDwsJCp93CwgLV1dWPvCgiIiIiU9MrJL3wwguYOXMmbty4IbVdv34dMTExGDhwoMEWR0RERGQqeoWk9evX4+7du/D09ET79u3RoUMHeHl54e7du1i3bp2h10hERERkdHrdk+Tm5oacnByo1Wp8//33EEKgS5cuGDRokKHXR0RERGQSjQ5JlZWVsLKywqlTpxAaGorQ0NCmWBcRERGRSTX6cpu5uTk8PDxQVVXVFOshIiIieizodU/SggULEBsbi5s3bxp6PURERESPBb3uSVq7di3++9//wtXVFR4eHrCxsdHanpOTY5DFEREREZmKXmeSRo4ciblz5yI2NhavvvoqXnrpJa2vxkhOToaXlxesrKzg7++Po0eP1tn/yJEj8Pf3h5WVFby9vZGSkqK1/dy5cxg9ejQ8PT2hUCiQmJioM8bixYuhUCi0vpydnRu1biIiIvpja9SZpLKyMsydOxefffYZNBoNBg4ciHXr1qFt27Z6Tb5r1y7MmjULycnJ6Nu3L/7+979j8ODBOH/+PNzd3XX65+XlYciQIZg6dSq2bduG//znP4iOjoaDgwNGjx4trdHb2xt//vOfERMTU+vcXbt2xf79+6XHZmZmeh0DERER/TE1KiQtWrQIaWlpGD9+PKytrbF9+3a8+eab+OSTT/SafM2aNZgyZQoiIyMBAImJidi3bx82bNiAhIQEnf4pKSlwd3eXzg75+Pjg5MmTWL16tRSSnn32WTz77LMAgPnz59c6t7m5Oc8eERERUa0aFZL27NmD1NRUjB07FgAwfvx49O3bF1VVVY0+E1NRUYHs7GydIBMWFobMzEzZfbKysnQ+Gy48PBypqanQaDSyH5VSm0uXLsHV1RVKpRK9e/fG8uXL4e3tXWv/8vJylJeXS49LS0sBABqNBhqNpsHzNkTNeIYel7SxzoZjjmpoNBqY4/7HEj34/cN/1qjpw/obBp/PxsE6G0dT1rkxYzYqJF29ehXBwcHS4+eeew7m5ua4ceMG3NzcGjMUiouLUVVVBScnJ612JycnFBYWyu5TWFgo27+yshLFxcVwcXFp0Ny9e/fG1q1b0bFjR/z0009YtmwZgoKCcO7cOdjb28vuk5CQgCVLlui0Z2RkoHnz5g2at7HUanWTjEvaWOdHN6Q1kJ6ejiGt7z9+8PsaYa2LtB7X9ElPTzfSKp8OfD4bB+tsHE1R57Kysgb3bVRIqqqqgqWlpfYA5uaorKxszDBaFAqF1mMhhE5bff3l2usyePBg6Xs/Pz8EBgaiffv22LJlC1Qqlew+sbGxWttKS0vh5uaGsLAw2NraNnjuhtBoNFCr1QgNDW3U2TFqHNbZcKZ/nIP143th+sf3X9n64PfmqEZY6yJk3HJE5QOvFanps358L5Os+Y+Gz2fjYJ2NoynrXHMlqCEaFZKEEJg0aRKUSqXU9ttvvyEqKkrrbQD27NlT71ht27aFmZmZzlmjoqIinbNFNZydnWX7m5ub13oGqCFsbGzg5+eHS5cu1dpHqVRqHXcNCwuLJvtFacqx6Xes86OrRDNYWFhIIejB7x/s82BbTR/W3rD4fDYO1tk4mqLOjRmvUW8BMHHiRDg6OsLOzk76eu211+Dq6qrV1hCWlpbw9/fXOZWmVqsRFBQku09gYKBO/4yMDAQEBDxSEcvLy3HhwoUGX64jIiKiP75GnUn68MMPDTq5SqVCREQEAgICEBgYiI0bNyI/Px9RUVEA7l/iun79OrZu3QoAiIqKwvr166FSqTB16lRkZWUhNTUVO3bskMasqKjA+fPnpe+vX7+OU6dOoUWLFujQoQMAYM6cORg+fDjc3d1RVFSEZcuWobS0FBMnTjTo8REREdGTS6933DaUMWPGoKSkBEuXLkVBQQF8fX2Rnp4ODw8PAEBBQQHy8/Ol/l5eXkhPT0dMTAySkpLg6uqKtWvXSi//B4AbN26gZ8+e0uPVq1dj9erVCAkJweHDhwEA165dw7hx41BcXAwHBwf06dMHx44dk+YlIiIiMmlIAoDo6GhER0fLbktLS9NpCwkJqfNjTzw9PaWbuWuzc+fORq2RiIiInj56fSwJERER0R8dQxIRERGRDIYkIiIiIhkMSUREREQyGJKIiIiIZDAkEREREclgSCIiIiKSwZBEREREJIMhiYiIiEgGQxIRERGRDIYkIiIiIhkMSUREREQyGJKIiIiIZDAkEdEjmZJ2QuvPh79v6P5ERI8bhiQiIiIiGQxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRGQSfKdtInrcMSQRERERyWBIIiIiIpLBkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRERERDIYkoiIiIhkMCQRERERyWBIIiK9GfJds/kO3ET0uGFIIiIiIpLBkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGSYPScnJyfDy8oKVlRX8/f1x9OjROvsfOXIE/v7+sLKygre3N1JSUrS2nzt3DqNHj4anpycUCgUSExMNMi8RERE9XUwaknbt2oVZs2YhPj4eubm5CA4OxuDBg5Gfny/bPy8vD0OGDEFwcDByc3MRFxeHGTNmYPfu3VKfsrIyeHt7Y8WKFXB2djbIvERERPT0MWlIWrNmDaZMmYLIyEj4+PggMTERbm5u2LBhg2z/lJQUuLu7IzExET4+PoiMjMTkyZOxevVqqc+zzz6L9957D2PHjoVSqTTIvERERPT0MTfVxBUVFcjOzsb8+fO12sPCwpCZmSm7T1ZWFsLCwrTawsPDkZqaCo1GAwsLiyaZFwDKy8tRXl4uPS4tLQUAaDQaaDSaeudtjJrxDD0uaWOdH505qhvcp66+Go0G5qjmz+IR8PlsHKyzcTRlnRszpslCUnFxMaqqquDk5KTV7uTkhMLCQtl9CgsLZftXVlaiuLgYLi4uTTIvACQkJGDJkiU67RkZGWjevHm98+pDrVY3ybikjXXW35DWDe8b1rqo1m3p6ekY0vr+n/Ro+Hw2DtbZOJqizmVlZQ3ua7KQVEOhUGg9FkLotNXXX67d0PPGxsZCpVJJj0tLS+Hm5oawsDDY2to2au76aDQaqNVqhIaGNujsGOmHdX500z/OqbePOaoR1roIGbccUVnLFf7143th+sc5Wn9S4/D5bByss3E0ZZ1rrgQ1hMlCUtu2bWFmZqZz9qaoqEjnLE8NZ2dn2f7m5uawt7dvsnkBQKlUyt7jZGFh0WS/KE05Nv2OddZfbaGntr619bewsEAlmmn9Sfrh89k4WGfjaIo6N2Y8k924bWlpCX9/f51TaWq1GkFBQbL7BAYG6vTPyMhAQEBAgw9an3mJiIjo6WPSy20qlQoREREICAhAYGAgNm7ciPz8fERFRQG4f4nr+vXr2Lp1KwAgKioK69evh0qlwtSpU5GVlYXU1FTs2LFDGrOiogLnz5+Xvr9+/TpOnTqFFi1aoEOHDg2al4iIiMikIWnMmDEoKSnB0qVLUVBQAF9fX6Snp8PDwwMAUFBQoPXeRV5eXkhPT0dMTAySkpLg6uqKtWvXYvTo0VKfGzduoGfPntLj1atXY/Xq1QgJCcHhw4cbNC8RERGRyW/cjo6ORnR0tOy2tLQ0nbaQkBDk5NR+s6inp6d0M7e+8xIRERGZ/GNJiIiIiB5HDElEREREMhiSiIiIiGQwJBERERHJYEgiIiIiksGQRERERCSDIYmIiIhIBkMSERERkQyGJCIiIiIZDElEREREMhiSiIiIiGQwJBERERHJYEgiIiIiksGQRER6mZJ2wtRLICJqUgxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRERERDIYkoiIiIhkMCQRERERyWBIIqJGm5J24okal4hIHwxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkw+QhKTk5GV5eXrCysoK/vz+OHj1aZ/8jR47A398fVlZW8Pb2RkpKik6f3bt3o0uXLlAqlejSpQv27t2rtX3x4sVQKBRaX87OzgY9LiIiInqymTQk7dq1C7NmzUJ8fDxyc3MRHByMwYMHIz8/X7Z/Xl4ehgwZguDgYOTm5iIuLg4zZszA7t27pT5ZWVkYM2YMIiIicPr0aUREROAvf/kLjh8/rjVW165dUVBQIH2dPXu2SY+ViIiIniwmDUlr1qzBlClTEBkZCR8fHyQmJsLNzQ0bNmyQ7Z+SkgJ3d3ckJibCx8cHkZGRmDx5MlavXi31SUxMRGhoKGJjY9G5c2fExsZi4MCBSExM1BrL3Nwczs7O0peDg0NTHioRERE9YcxNNXFFRQWys7Mxf/58rfawsDBkZmbK7pOVlYWwsDCttvDwcKSmpkKj0cDCwgJZWVmIiYnR6fNwSLp06RJcXV2hVCrRu3dvLF++HN7e3rWut7y8HOXl5dLj0tJSAIBGo4FGo6n3eBujZjxDj0vaWGf9maO60X3r2kej0Wht58+k8fh8Ng7W2Tiass6NGdNkIam4uBhVVVVwcnLSandyckJhYaHsPoWFhbL9KysrUVxcDBcXl1r7PDhm7969sXXrVnTs2BE//fQTli1bhqCgIJw7dw729vaycyckJGDJkiU67RkZGWjevHmDjrmx1Gp1k4xL2ljnxhvSuvH7hLUuqnVbenq61pjp6el6rIoAPp+NhXU2jqaoc1lZWYP7miwk1VAoFFqPhRA6bfX1f7i9vjEHDx4sfe/n54fAwEC0b98eW7ZsgUqlkp03NjZWa1tpaSnc3NwQFhYGW1vbWterD41GA7VajdDQUFhYWBh0bPod66y/6R/nNLivOaoR1roIGbccUdnAK/zrx/fSd2lPLT6fjYN1No6mrHPNlaCGMFlIatu2LczMzHTOGhUVFemcCarh7Ows29/c3Fw6A1Rbn9rGBAAbGxv4+fnh0qVLtfZRKpVQKpU67RYWFk32i9KUY9PvWOfGa2jYeXifhu7Hn4f++Hw2DtbZOJqizo0Zz2Q3bltaWsLf31/nVJparUZQUJDsPoGBgTr9MzIyEBAQIB10bX1qGxO4f7/RhQsX4OLios+hEBER0R+QSV/dplKp8I9//AObN2/GhQsXEBMTg/z8fERFRQG4f4lrwoQJUv+oqChcuXIFKpUKFy5cwObNm5Gamoo5c+ZIfWbOnImMjAysXLkS33//PVauXIn9+/dj1qxZUp85c+bgyJEjyMvLw/Hjx/HKK6+gtLQUEydONNqxExER0ePNpPckjRkzBiUlJVi6dCkKCgrg6+uL9PR0eHh4AAAKCgq03jPJy8sL6enpiImJQVJSElxdXbF27VqMHj1a6hMUFISdO3diwYIFWLhwIdq3b49du3ahd+/eUp9r165h3LhxKC4uhoODA/r06YNjx45J8xIRERGZ/Mbt6OhoREdHy25LS0vTaQsJCUFOTt03jb7yyit45ZVXat2+c+fORq2RiIiInj4m/1gSIiIioscRQxIRERGRDIYkIiIiIhkmvyeJiJ4cU9JOmHoJRERGwzNJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRERERDIYkoiIiIhkMCQR0WOJH4FCRKbGkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiOplqne/npJ2Qvoy5TqI6OnEkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiABov5u13PfGfLfr+ubiO28TkTEwJBERERHJYEgiIiIiksGQRERERCSDIYmIiIhIhslDUnJyMry8vGBlZQV/f38cPXq0zv5HjhyBv78/rKys4O3tjZSUFJ0+u3fvRpcuXaBUKtGlSxfs3bv3keclIiKip4tJQ9KuXbswa9YsxMfHIzc3F8HBwRg8eDDy8/Nl++fl5WHIkCEIDg5Gbm4u4uLiMGPGDOzevVvqk5WVhTFjxiAiIgKnT59GREQE/vKXv+D48eN6z0tERERPH5OGpDVr1mDKlCmIjIyEj48PEhMT4ebmhg0bNsj2T0lJgbu7OxITE+Hj44PIyEhMnjwZq1evlvokJiYiNDQUsbGx6Ny5M2JjYzFw4EAkJibqPS8RERE9fUwWkioqKpCdnY2wsDCt9rCwMGRmZsruk5WVpdM/PDwcJ0+ehEajqbNPzZj6zEtERERPH3NTTVxcXIyqqio4OTlptTs5OaGwsFB2n8LCQtn+lZWVKC4uhouLS619asbUZ14AKC8vR3l5ufT4zp07AICbN29KAc1QNBoNysrKUFJSAgsLC4OOTb9jnbVV/3oXJSUlst8/0rioRpmyDNW/3kX1I/y/rKSkRFrXg+uj+/h8Ng7W2Tiass53797/O00IUW9fk4WkGgqFQuuxEEKnrb7+D7c3ZMzGzpuQkIAlS5botHt5edW6D9GTJi1a/vtH9Q8DjFGznof/JCLSx927d2FnZ1dnH5OFpLZt28LMzEzn7E1RUZHOWZ4azs7Osv3Nzc1hb29fZ5+aMfWZFwBiY2OhUqmkx9XV1bh58ybs7e3rDFf6KC0thZubG65evQpbW1uDjk2/Y52Ng3U2DtbZOFhn42jKOgshcPfuXbi6utbb12QhydLSEv7+/lCr1Rg1apTUrlar8dJLL8nuExgYiC+++EKrLSMjAwEBAdLpuMDAQKjVasTExGj1CQoK0nteAFAqlVAqlVptrVq1atjB6snW1pa/hEbAOhsH62wcrLNxsM7G0VR1ru8MUg2TXm5TqVSIiIhAQEAAAgMDsXHjRuTn5yMqKgrA/bM3169fx9atWwEAUVFRWL9+PVQqFaZOnYqsrCykpqZix44d0pgzZ85Ev379sHLlSrz00kv45z//if379+Obb75p8LxEREREJg1JY8aMQUlJCZYuXYqCggL4+voiPT0dHh4eAICCggKt9y7y8vJCeno6YmJikJSUBFdXV6xduxajR4+W+gQFBWHnzp1YsGABFi5ciPbt22PXrl3o3bt3g+clIiIiUoiG3N5NRlVeXo6EhATExsbqXOIjw2GdjYN1Ng7W2ThYZ+N4XOrMkEREREQkw+Sf3UZERET0OGJIIiIiIpLBkEREREQkgyGJiIiISAZD0mMmOTkZXl5esLKygr+/P44ePWrqJT1REhIS8Oyzz6Jly5ZwdHTEyJEjcfHiRa0+QggsXrwYrq6usLa2Rv/+/XHu3DmtPuXl5XjrrbfQtm1b2NjYYMSIEbh27ZoxD+WJkZCQAIVCgVmzZkltrLHhXL9+Ha+99hrs7e3RvHlz9OjRA9nZ2dJ21vrRVVZWYsGCBfDy8oK1tTW8vb2xdOlSVFdXS31Y58b7+uuvMXz4cLi6ukKhUOCzzz7T2m6omt66dQsRERGws7ODnZ0dIiIicPv2bcMchKDHxs6dO4WFhYXYtGmTOH/+vJg5c6awsbERV65cMfXSnhjh4eHiww8/FN999504deqUGDp0qHB3dxe//PKL1GfFihWiZcuWYvfu3eLs2bNizJgxwsXFRZSWlkp9oqKiRLt27YRarRY5OTliwIABonv37qKystIUh/XY+vbbb4Wnp6fo1q2bmDlzptTOGhvGzZs3hYeHh5g0aZI4fvy4yMvLE/v37xf//e9/pT6s9aNbtmyZsLe3F19++aXIy8sTn3zyiWjRooVITEyU+rDOjZeeni7i4+PF7t27BQCxd+9ere2GqumLL74ofH19RWZmpsjMzBS+vr5i2LBhBjkGhqTHyHPPPSeioqK02jp37izmz59vohU9+YqKigQAceTIESGEENXV1cLZ2VmsWLFC6vPbb78JOzs7kZKSIoQQ4vbt28LCwkLs3LlT6nP9+nXRrFkz8dVXXxn3AB5jd+/eFX/605+EWq0WISEhUkhijQ1n3rx54vnnn691O2ttGEOHDhWTJ0/Wanv55ZfFa6+9JoRgnQ3h4ZBkqJqeP39eABDHjh2T+mRlZQkA4vvvv3/kdfNy22OioqIC2dnZCAsL02oPCwtDZmamiVb15Ltz5w4AoE2bNgCAvLw8FBYWatVZqVQiJCREqnN2djY0Go1WH1dXV/j6+vJn8YBp06Zh6NChGDRokFY7a2w4n3/+OQICAvDnP/8Zjo6O6NmzJzZt2iRtZ60N4/nnn8eBAwfwww8/AABOnz6Nb775BkOGDAHAOjcFQ9U0KysLdnZ2Wp+q0adPH9jZ2Rmk7ib9WBL6XXFxMaqqquDk5KTV7uTkhMLCQhOt6skmhIBKpcLzzz8PX19fAJBqKVfnK1euSH0sLS3RunVrnT78Wdy3c+dO5OTk4MSJEzrbWGPD+d///ocNGzZApVIhLi4O3377LWbMmAGlUokJEyaw1gYyb9483LlzB507d4aZmRmqqqrw7rvvYty4cQD4nG4KhqppYWEhHB0ddcZ3dHQ0SN0Zkh4zCoVC67EQQqeNGmb69Ok4c+aM1ocb19CnzvxZ3Hf16lXMnDkTGRkZsLKyqrUfa/zoqqurERAQgOXLlwMAevbsiXPnzmHDhg2YMGGC1I+1fjS7du3Ctm3bsH37dnTt2hWnTp3CrFmz4OrqiokTJ0r9WGfDM0RN5fobqu683PaYaNu2LczMzHSSb1FRkU7Spvq99dZb+Pzzz3Ho0CE888wzUruzszMA1FlnZ2dnVFRU4NatW7X2eZplZ2ejqKgI/v7+MDc3h7m5OY4cOYK1a9fC3NxcqhFr/OhcXFzQpUsXrTYfHx/pg7/5fDaMuXPnYv78+Rg7diz8/PwQERGBmJgYJCQkAGCdm4Khaurs7IyffvpJZ/yff/7ZIHVnSHpMWFpawt/fH2q1WqtdrVYjKCjIRKt68gghMH36dOzZswcHDx6El5eX1nYvLy84Oztr1bmiogJHjhyR6uzv7w8LCwutPgUFBfjuu+/4swAwcOBAnD17FqdOnZK+AgICMH78eJw6dQre3t6ssYH07dtX5y0sfvjhB3h4eADg89lQysrK0KyZ9j+HZmZm0lsAsM6GZ6iaBgYG4s6dO/j222+lPsePH8edO3cMU/dHvvWbDKbmLQBSU1PF+fPnxaxZs4SNjY24fPmyqZf2xHjzzTeFnZ2dOHz4sCgoKJC+ysrKpD4rVqwQdnZ2Ys+ePeLs2bNi3Lhxsi87feaZZ8T+/ftFTk6OeOGFF57ql/LW58FXtwnBGhvKt99+K8zNzcW7774rLl26JD7++GPRvHlzsW3bNqkPa/3oJk6cKNq1aye9BcCePXtE27Ztxdtvvy31YZ0b7+7duyI3N1fk5uYKAGLNmjUiNzdXelsbQ9X0xRdfFN26dRNZWVkiKytL+Pn58S0A/qiSkpKEh4eHsLS0FL169ZJeuk4NA0D268MPP5T6VFdXi0WLFglnZ2ehVCpFv379xNmzZ7XG+fXXX8X06dNFmzZthLW1tRg2bJjIz8838tE8OR4OSayx4XzxxRfC19dXKJVK0blzZ7Fx40at7az1oystLRUzZ84U7u7uwsrKSnh7e4v4+HhRXl4u9WGdG+/QoUOyfx9PnDhRCGG4mpaUlIjx48eLli1bipYtW4rx48eLW7duGeQYFEII8ejno4iIiIj+WHhPEhEREZEMhiQiIiIiGQxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiIzu8uXLUCgUOHXqlKmXIvn+++/Rp08fWFlZoUePHqZeDhE9BhiSiJ5CkyZNgkKhwIoVK7TaP/vss6f2E8sXLVoEGxsbXLx4EQcOHJDtU1RUhL/+9a9wd3eHUqmEs7MzwsPDkZWVZeTVEpExMCQRPaWsrKywcuVKnU/YfpJVVFTove+PP/6I559/Hh4eHrC3t5ftM3r0aJw+fRpbtmzBDz/8gM8//xz9+/fHzZs39Z6XiB5fDElET6lBgwbB2dkZCQkJtfZZvHixzqWnxMREeHp6So8nTZqEkSNHYvny5XByckKrVq2wZMkSVFZWYu7cuWjTpg2eeeYZbN68WWf877//HkFBQbCyskLXrl1x+PBhre3nz5/HkCFD0KJFCzg5OSEiIgLFxcXS9v79+2P69OlQqVRo27YtQkNDZY+juroaS5cuxTPPPAOlUokePXrgq6++krYrFApkZ2dj6dKlUCgUWLx4sc4Yt2/fxjfffIOVK1diwIAB8PDwwHPPPYfY2FgMHToUgPxlxNu3b0OhUGgd27lz5zB06FDY2tqiZcuWCA4Oxo8//iht37x5M7p27QqlUgkXFxdMnz5d2nbnzh288cYbcHR0hK2tLV544QWcPn1a2n769GkMGDAALVu2hK2tLfz9/XHy5EkAwJUrVzB8+HC0bt0aNjY26Nq1K9LT0xtc708//RR+fn6wtraGvb09Bg0ahHv37snWnOiPgCGJ6CllZmaG5cuXY926dbh27dojjXXw4EHcuHEDX3/9NdasWYPFixdj2LBhaN26NY4fP46oqChERUXh6tWrWvvNnTsXs2fPRm5uLoKCgjBixAiUlJQAAAoKChASEoIePXrg5MmT+Oqrr/DTTz/hL3/5i9YYW7Zsgbm5Of7zn//g73//u+z6PvjgA/ztb3/D6tWrcebMGYSHh2PEiBG4dOmSNFfXrl0xe/ZsFBQUYM6cOTpjtGjRAi1atMBnn32G8vJyvWt1/fp19OvXD1ZWVjh48CCys7MxefJkVFZWAgA2bNiAadOm4Y033sDZs2fx+eefo0OHDgAAIQSGDh2KwsJCpKenIzs7G7169cLAgQOls1njx4/HM888gxMnTiA7Oxvz58+HhYUFAGDatGkoLy/H119/jbNnz2LlypVo0aJFg+pdUFCAcePGYfLkybhw4QIOHz6Ml19+Gfz4T/pDM8jH5BLRE2XixInipZdeEkII0adPHzF58mQhhBB79+4VD/61sGjRItG9e3etfd9//33h4eGhNZaHh4eoqqqS2jp16iSCg4Olx5WVlcLGxkbs2LFDCCFEXl6eACBWrFgh9dFoNOKZZ54RK1euFEIIsXDhQhEWFqY199WrVwUAcfHiRSGEECEhIaJHjx71Hq+rq6t49913tdqeffZZER0dLT3u3r27WLRoUZ3jfPrpp6J169bCyspKBAUFidjYWHH69Glpe81x5ebmSm23bt0SAMShQ4eEEELExsYKLy8vUVFRUeta4+PjZbcdOHBA2Nrait9++02rvX379uLvf/+7EEKIli1birS0NNn9/fz8xOLFi2W31Vfv7OxsAUBcvnxZdn+iPyKeSSJ6yq1cuRJbtmzB+fPn9R6ja9euaNbs979OnJyc4OfnJz02MzODvb09ioqKtPYLDAyUvjc3N0dAQAAuXLgAAMjOzsahQ4ekMzgtWrRA586dAUDr0lRAQECdaystLcWNGzfQt29frfa+fftKczXU6NGjcePGDXz++ecIDw/H4cOH0atXL6SlpTV4jFOnTiE4OFg6u/OgoqIi3LhxAwMHDpTdNzs7G7/88gvs7e216pKXlyfVRKVSITIyEoMGDcKKFSu0ajVjxgwsW7YMffv2xaJFi3DmzBmtseuqd/fu3TFw4ED4+fnhz3/+MzZt2vSHup+NSA5DEtFTrl+/fggPD0dcXJzOtmbNmulcTtFoNDr9Hv4HX6FQyLZVV1fXu56aV9dVV1dj+PDhOHXqlNbXpUuX0K9fP6m/jY1NvWM+OG4NIYRer+SzsrJCaGgo/u///g+ZmZmYNGkSFi1aBABSUHywZg/Xy9rautax69oG3K+Ji4uLTk0uXryIuXPnArh/H1nNPU8HDx5Ely5dsHfvXgBAZGQk/ve//yEiIgJnz55FQEAA1q1bJ41dV73NzMygVqvx73//G126dMG6devQqVMn5OXlNbKCRE8OhiQiwooVK/DFF18gMzNTq93BwQGFhYVa/+gb8r2Njh07Jn1fWVmJ7Oxs6exFr169cO7cOXh6eqJDhw5aXw0NRgBga2sLV1dXfPPNN1rtmZmZ8PHxeeRj6NKli3TzsoODA4D79+/UeLhe3bp1w9GjR2XDZsuWLeHp6VnrWxD06tULhYWFMDc316lJ27ZtpX4dO3ZETEwMMjIy8PLLL+PDDz+Utrm5uSEqKgp79uzB7NmzsWnTJmns+uqtUCjQt29fLFmyBLm5ubC0tJQCGNEfEUMSEcHPzw/jx4+XzirU6N+/P37++WesWrUKP/74I5KSkvDvf//bYPMmJSVh7969+P777zFt2jTcunULkydPBnD/JuObN29i3Lhx+Pbbb/G///0PGRkZmDx5Mqqqqho1z9y5c7Fy5Urs2rULFy9exPz583Hq1CnMnDmzwWOUlJTghRdewLZt23DmzBnk5eXhk08+wapVq/DSSy8BuH8mqE+fPlixYgXOnz+Pr7/+GgsWLNAaZ/r06SgtLcXYsWNx8uRJXLp0CR999BEuXrwI4P6ZoL/97W9Yu3YtLl26hJycHOnnMmjQIAQGBmLkyJHYt28fLl++jMzMTCxYsAAnT57Er7/+iunTp+Pw4cO4cuUK/vOf/+DEiRNSGJw1axb27duHvLw85OTk4ODBg9K2+up9/PhxLF++HCdPnkR+fj727NmDn3/+2SBBk+ixZdpboojIFB68cbvG5cuXhVKpFA//tbBhwwbh5uYmbGxsxIQJE8S7776rc+P2w2OFhISImTNnarV5eHiI999/Xwjx+w3O27dvF7179xaWlpbCx8dHHDhwQGufH374QYwaNUq0atVKWFtbi86dO4tZs2aJ6urqWueRU1VVJZYsWSLatWsnLCwsRPfu3cW///1vrT713bj922+/ifnz54tevXoJOzs70bx5c9GpUyexYMECUVZWJvU7f/686NOnj7C2thY9evQQGRkZWjduCyHE6dOnRVhYmGjevLlo2bKlCA4OFj/++KO0PSUlRXTq1ElYWFgIFxcX8dZbb0nbSktLxVtvvSVcXV2FhYWFcHNzE+PHjxf5+fmivLxcjB07Vri5uQlLS0vh6uoqpk+fLn799VchhBDTp08X7du3F0qlUjg4OIiIiAhRXFzcoHqfP39ehIeHCwcHB6FUKkXHjh3FunXr6q090ZNMIQRfv0lERET0MF5uIyIiIpLBkEREREQkgyGJiIiISAZDEhEREZEMhiQiIiIiGQxJRERERDIYkoiIiIhkMCQRERERyWBIIiIiIpLBkEREREQkgyGJiIiISAZDEhEREZGM/w+ypr1JMkVpVgAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 640x480 with 1 Axes>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "#Question.5 Generate a random sample of size 1000 from a binomial distribution with probability of\n",
    "#success 0.4 and plot a histogram of the results using matplotlib.\n",
    "#Answer.5 : \n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# Parameters\n",
    "n = 1000  # Sample size\n",
    "p = 0.4   # Probability of success\n",
    "\n",
    "# Generate random sample from binomial distribution\n",
    "random_sample = np.random.binomial(n, p, size=n)\n",
    "\n",
    "# Plot histogram\n",
    "plt.hist(random_sample, bins=np.arange(-0.5, n + 1.5, 1), align='mid', density=True, alpha=0.7)\n",
    "plt.xlabel('Number of Successes')\n",
    "plt.ylabel('Probability')\n",
    "plt.title('Histogram of Binomial Distribution')\n",
    "plt.grid(True)\n",
    "plt.show()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b7696be4-c245-4be0-920a-f0019df1534b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CDF at x = 2: 0.42319008112684364\n"
     ]
    }
   ],
   "source": [
    "#Question.6 Write a Python function to calculate the cumulative distribution function of a \n",
    "#Poisson distribution with given mean at a given point.\n",
    "#Answer.6 : \n",
    "import scipy.stats as stats\n",
    "\n",
    "def poisson_cdf(mean, x):\n",
    "    \"\"\"\n",
    "    Calculate the Cumulative Distribution Function (CDF) of a Poisson distribution\n",
    "    at a given point x, with the given mean.\n",
    "    \n",
    "    Args:\n",
    "        mean (float): Mean of the Poisson distribution.\n",
    "        x (int): Point at which to calculate the CDF.\n",
    "    \n",
    "    Returns:\n",
    "        float: Cumulative Distribution Function value at the given point x.\n",
    "    \"\"\"\n",
    "    cdf_value = stats.poisson.cdf(x, mu=mean)\n",
    "    return cdf_value\n",
    "\n",
    "# Example usage\n",
    "mean = 3\n",
    "x_value = 2\n",
    "cdf_at_x = poisson_cdf(mean, x_value)\n",
    "print(f\"CDF at x = {x_value}: {cdf_at_x}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c250e6dd-bce3-45ef-94ea-a37a1e46a68c",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.7 How Binomial distribution different from Poisson distribution?\n",
    "#Answer.7 The Binomial and Poisson distributions are two distinct probability\n",
    "#distributions used to model different types of random processes. While they\n",
    "#share some similarities, they are applied in different contexts and have\n",
    "#distinct characteristics. \n",
    "\n",
    "#Here's how they differ:\n",
    "\n",
    "#number of Parameters: The Binomial distribution has two parameters (n and p),\n",
    "#while the Poisson distribution has one parameter (λ).\n",
    "\n",
    "#application: Binomial distribution is used when dealing with a fixed number \n",
    "#of trials with binary outcomes, while Poisson distribution is used for modeling rare\n",
    "#and random events in a fixed interval.\n",
    "\n",
    "#Probability of Success: In the Binomial distribution, the probability of success\n",
    "#remains constant across all trials. In the Poisson distribution, the parameter λ \n",
    "#represents the average rate of event occurrences.\n",
    "\n",
    "#Events: The Binomial distribution deals with discrete events involving successes\n",
    "#and failures. The Poisson distribution deals with the occurrence of rare events\n",
    "#in continuous time or space.\n",
    "\n",
    "#Relation: In certain cases, the Poisson distribution can be considered a limiting \n",
    "#case of the Binomial distribution when the number of trials is very large and the \n",
    "#probability of success is very small, while keeping the expected number of successes \n",
    "#constant (λ = n * p)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "fa63f5a7-612d-4e61-a350-e8615b519972",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Sample Mean: 5.06\n",
      "Sample Variance: 5.312399999999999\n"
     ]
    }
   ],
   "source": [
    "#Question.8 Generate a random sample of size 1000 from a Poisson distribution with mean 5 \n",
    "#and calculate the sample mean and variance.\n",
    "#Answer.8 : \n",
    "\n",
    "import numpy as np\n",
    "\n",
    "# Parameters\n",
    "sample_size = 1000\n",
    "mean = 5\n",
    "\n",
    "# Generate random sample from Poisson distribution\n",
    "random_sample = np.random.poisson(mean, size=sample_size)\n",
    "\n",
    "# Calculate sample mean and variance\n",
    "sample_mean = np.mean(random_sample)\n",
    "sample_variance = np.var(random_sample)\n",
    "\n",
    "print(f\"Sample Mean: {sample_mean}\")\n",
    "print(f\"Sample Variance: {sample_variance}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d3039f74-7b13-41a7-a1ac-380f70748c5c",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.9 How mean and variance are related in Binomial distribution and Poisson distribution?\n",
    "#Answer.9 The mean and variance of both the Binomial and Poisson distributions are related\n",
    "#to the distribution's parameters and characteristics, but they are related differently \n",
    "#for each distribution.\n",
    "\n",
    "#Binomial Distribution:\n",
    "\n",
    "#For a Binomial distribution with parameters n (number of trials) and p \n",
    "#(probability of success on each trial), the mean and variance are given by:\n",
    "\n",
    "#Mean (μ) = n * p\n",
    "#Variance (σ^2) = n * p * (1 - p)\n",
    "\n",
    "#In the Binomial distribution, the variance is influenced by both the number of\n",
    "#trials n and the probability of success p. As n increases while keeping p fixed,\n",
    "#the variance tends to increase, indicating greater variability in outcomes. Similarly,\n",
    "#as p approaches 0 or 1 while keeping n fixed, the variance also tends to decrease.\n",
    "\n",
    "#Poisson Distribution:\n",
    "#For a Poisson distribution with parameter λ (average rate of event occurrences),\n",
    "#the mean and variance are both equal to λ:\n",
    "\n",
    "#Mean (μ) = λ\n",
    "#Variance (σ^2) = λ\n",
    "\n",
    "#In the Poisson distribution, the mean and variance are directly related and are\n",
    "#both equal to the parameter λ. This relationship implies that the spread or \n",
    "#variability of the distribution is solely determined by the average rate of\n",
    "#event occurrences. As λ increases, both the mean and variance increase, indicating \n",
    "#a broader spread of events.\n",
    "\n",
    "#Comparison:\n",
    "#In summary, in the Binomial distribution, the variance is influenced by both the \n",
    "#number of trials and the probability of success, while in the Poisson distribution, \n",
    "#the variance is solely determined by the mean (average rate of occurrences). The \n",
    "#relationship between mean and variance is different for each distribution, but\n",
    "#both provide insights into the distribution's characteristics and the spread of \n",
    "#possible outcomes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4780fc69-0588-44a8-979e-1e89f52872c1",
   "metadata": {},
   "outputs": [],
   "source": [
    "#Question.10 In normal distribution with respect to mean position, where does the\n",
    "#least frequent data appear?\n",
    "#Answer.10 In a normal distribution, which is symmetric and bell-shaped, the least\n",
    "#frequent data points occur in the tails of the distribution, farthest from the mean. \n",
    "#The tails of the normal distribution represent the extreme values, and these values \n",
    "#occur with lower frequencies compared to the values closer to the mean.\n",
    "\n",
    "#The mean of a normal distribution is the central point of the distribution and \n",
    "#represents the highest point of the curve. As you move away from the mean in \n",
    "#either direction towards the tails, the frequency of data points decreases. \n",
    "#This is a key characteristic of the normal distribution's symmetric and bell-shaped\n",
    "#nature.\n",
    "\n",
    "#In statistical terms, the \"tails\" of a normal distribution refer to the portions of the \n",
    "#distribution that are located beyond a certain number of standard deviations from\n",
    "#the mean. The data points in these tails are the least frequent and are considered \n",
    "#outliers or extreme values. The percentage of data within a certain number of standard\n",
    "#deviations from the mean is given by the empirical rule (also known as the 68-95-99.7 \n",
    "#rule), which states that approximately:\n",
    "\n",
    "#About 68% of the data falls within one standard deviation of the mean.\n",
    "#About 95% falls within two standard deviations.\n",
    "#About 99.7% falls within three standard deviations.\n",
    "#So, the data points that are more than three standard deviations away from the\n",
    "#mean (in the tails) are the least frequent and most extreme values in a normal distribution."
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
